// Generated by .

	public partial class GameDefine 
	{

		public class CreditsQA_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "units\\nightelf\\HeroKeeperoftheGrove\\HeroKeeperoftheGrove_portrait.mdx" );
				Preload( "Textures\\Keeperofthegrove.blp" );
				Preload( "units\\demon\\ChaosHellscream\\ChaosHellscream_portrait.mdx" );
				Preload( "Textures\\HellscreamChaos.blp" );
				Preload( "units\\creeps\\RockGolem\\RockGolem.mdx" );
				Preload( "units\\Creeps\\RockGolem\\rocktile.blp" );
				Preload( "units\\Creeps\\RockGolem\\RockGolem2.blp" );
				Preload( "buildings\\undead\\SacrificialPit\\SacrificialPit.mdx" );
				Preload( "buildings\\Undead\\SacrificialPit\\CreepySacrificialPit.blp" );
				Preload( "Textures\\Ghost2.blp" );
				Preload( "Textures\\GenericGlowX.blp" );
				Preload( "SharedModels\\UBirth.mdx" );
				Preload( "SharedModels\\UndeadBirth.blp" );
				Preload( "Textures\\Green_Glow2.blp" );
				Preload( "Textures\\AuraRune7Green.blp" );
				Preload( "Textures\\grad2b.blp" );
				Preload( "Textures\\GenericGlow5.blp" );
				Preload( "Textures\\Tornado2b.blp" );
				Preload( "buildings\\other\\FountainOfLifeBlood\\FountainOfLifeBlood.mdx" );
				Preload( "buildings\\Other\\FountainOfLifeBlood\\FountainOfLifeBlood.blp" );
				Preload( "Textures\\FountainOfLife.blp" );
				Preload( "buildings\\Other\\FountainOfLifeBlood\\FlareBlood.blp" );
				Preload( "Textures\\BackGround.blp" );
				PreloadEnd( 0.0 );
			}

		} // class CreditsQA_pld 

	}

