// Generated by .

	public partial class GameDefine 
	{

		public class CreditsLocalization_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "units\\creeps\\Harpy\\Harpy_portrait.mdx" );
				Preload( "units\\Creeps\\Harpy\\Harpy.blp" );
				Preload( "buildings\\nightelf\\AncientOfLore\\AncientOfLore_portrait.mdx" );
				Preload( "buildings\\NightElf\\AncientOfLore\\AncientOfLore.blp" );
				Preload( "units\\creeps\\GoblinSapper\\GoblinSapper_portrait.mdx" );
				Preload( "units\\Creeps\\GoblinSapper\\GoblinSapper.blp" );
				Preload( "units\\creeps\\ThunderLizard\\ThunderLizard_portrait.mdx" );
				Preload( "units\\Creeps\\ThunderLizard\\ThunderLizard.blp" );
				Preload( "units\\critters\\HighElfPeasant\\HighElfPeasant_portrait.mdx" );
				Preload( "Textures\\Priest.blp" );
				Preload( "units\\creeps\\MurlocNightcrawler\\MurlocNightcrawler_portrait.mdx" );
				Preload( "units\\Creeps\\MurlocNightCrawler\\MurlocNightCrawler.blp" );
				Preload( "units\\creeps\\Spider\\Spider_portrait.mdx" );
				Preload( "units\\Creeps\\Spider\\Spider.blp" );
				Preload( "units\\human\\HeroMountainKing\\HeroMountainKing_portrait.mdx" );
				Preload( "ReplaceableTextures\\HeroMountainKing\\heromountainking.blp" );
				Preload( "units\\creeps\\OgreMagi\\OgreMagi_portrait.mdx" );
				Preload( "units\\Creeps\\OgreMagi\\OgreMagi.blp" );
				Preload( "units\\creeps\\AzureDragon\\AzureDragon_portrait.mdx" );
				Preload( "Textures\\AzureDragon.blp" );
				Preload( "units\\creeps\\BansheeGhost\\BansheeGhost_portrait.mdx" );
				Preload( "units\\Creeps\\BansheeGhost\\BansheeGhost.blp" );
				Preload( "units\\critters\\VillagerKid\\VillagerKid_portrait.mdx" );
				Preload( "units\\Critters\\VillagerKid\\VillagerKid.blp" );
				Preload( "units\\creeps\\SylvanusWindrunner\\SylvanusWindrunner_portrait.mdx" );
				Preload( "units\\Creeps\\SylvanusWindrunner\\SylvanusWindrunner.blp" );
				Preload( "units\\creeps\\WindSerpent\\WindSerpent.mdx" );
				Preload( "units\\Creeps\\WindSerpent\\Dragonhawk.blp" );
				Preload( "Textures\\Blue_Star2.blp" );
				Preload( "SharedModels\\Feather2.mdx" );
				Preload( "SharedModels\\Feather1.blp" );
				Preload( "SharedModels\\Bones1.mdx" );
				Preload( "SharedModels\\Gutz1.mdx" );
				Preload( "SharedModels\\Feather1.mdx" );
				Preload( "units\\human\\WaterElemental\\WaterElemental_portrait.mdx" );
				Preload( "Textures\\Lords0000.blp" );
				Preload( "Textures\\Lords0001.blp" );
				Preload( "Textures\\Lords0002.blp" );
				Preload( "Textures\\Lords0003.blp" );
				Preload( "Textures\\Lords0004.blp" );
				Preload( "Textures\\Lords0005.blp" );
				Preload( "Textures\\Lords0006.blp" );
				Preload( "Textures\\Lords0007.blp" );
				Preload( "units\\Human\\WaterElemental\\WaterEnv1.blp" );
				Preload( "units\\critters\\Sheep\\Sheep_portrait.mdx" );
				Preload( "Textures\\SheepA.blp" );
				Preload( "units\\demon\\Infernal\\Infernal_portrait.mdx" );
				Preload( "units\\Demon\\Infernal\\Infernal.blp" );
				Preload( "Textures\\clouds_anim1_bw.blp" );
				Preload( "Textures\\Yellow_Star.blp" );
				Preload( "units\\creeps\\SatyrTrickster\\SatyrTrickster.mdx" );
				Preload( "units\\Creeps\\SatyrTrickster\\SatyrTrickster.blp" );
				Preload( "units\\orc\\Thrall\\Thrall_portrait.mdx" );
				Preload( "units\\Orc\\Thrall\\Thrall.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor01.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor02.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor03.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor04.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor05.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor06.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor07.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor08.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor09.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor10.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor11.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor13.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor14.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor15.blp" );
				Preload( "units\\orc\\Spiritwolf\\Spiritwolf_portrait.mdx" );
				Preload( "units\\Orc\\Spiritwolf\\FeralSpirit.blp" );
				Preload( "units\\demon\\ChaosWarlock\\ChaosWarlock_portrait.mdx" );
				Preload( "units\\Demon\\ChaosWarlock\\ChaosWarlock.blp" );
				Preload( "units\\demon\\felhound\\felhound_portrait.mdx" );
				Preload( "units\\Demon\\felhound\\FelHound.blp" );
				Preload( "units\\creeps\\GoblinZeppelin\\GoblinZeppelin_portrait.mdx" );
				Preload( "units\\Creeps\\GoblinZeppelin\\GoblinZepplin.blp" );
				Preload( "Textures\\grad1A.blp" );
				Preload( "units\\creeps\\GnollOverseer\\GnollOverseer.mdx" );
				Preload( "units\\Creeps\\GnollOverSeer\\GnollOverseer.blp" );
				Preload( "units\\critters\\Vulture\\Vulture_portrait.mdx" );
				Preload( "units\\Critters\\Vulture\\Carrionswarm.blp" );
				PreloadEnd( 0.0 );
			}

		} // class CreditsLocalization_pld 

	}

