// Generated by .

	public partial class GameDefine 
	{

		public class CreditsTeam1_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "units\\human\\Uther\\Uther_portrait.mdx" );
				Preload( "units\\Human\\Uther\\Uther.blp" );
				Preload( "units\\human\\Militia\\Militia.mdx" );
				Preload( "units\\Human\\Militia\\PeasantMilitia.blp" );
				Preload( "units\\human\\Militia\\Militia_portrait.mdx" );
				Preload( "units\\human\\MortarTeam\\MortarTeam.mdx" );
				Preload( "Textures\\MortarTeam.blp" );
				Preload( "Textures\\Clouds32_anim.blp" );
				Preload( "units\\human\\MortarTeam\\MortarTeam_portrait.mdx" );
				Preload( "units\\human\\Sorceress\\Sorceress.mdx" );
				Preload( "units\\Human\\Sorceress\\Sorceress.blp" );
				Preload( "units\\human\\Sorceress\\Sorceress_portrait.mdx" );
				Preload( "units\\creeps\\FurbolgPanda\\FurbolgPanda_portrait.mdx" );
				Preload( "units\\Creeps\\FurbolgPanda\\FurBolgPanda.blp" );
				Preload( "units\\undead\\Tichondrius\\Tichondrius_portrait.mdx" );
				Preload( "units\\Undead\\Tichondrius\\Tichondrius.blp" );
				Preload( "Textures\\Dust5ABlack.blp" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleSmall.blp" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleMed.blp" );
				Preload( "units\\demon\\Mannoroth\\Mannoroth_portrait.mdx" );
				Preload( "units\\Demon\\Mannoroth\\Mannoroth.blp" );
				Preload( "units\\human\\Rifleman\\Rifleman.mdx" );
				Preload( "units\\Human\\Rifleman\\Rifleman.blp" );
				Preload( "Textures\\Flame4.blp" );
				Preload( "units\\human\\Rifleman\\Rifleman_portrait.mdx" );
				Preload( "units\\human\\WarWagon\\WarWagon.mdx" );
				Preload( "Textures\\Steamtank.blp" );
				Preload( "Textures\\Clouds8x8Black.blp" );
				Preload( "Textures\\Shockwave10.blp" );
				Preload( "Textures\\LavaLump.blp" );
				Preload( "Textures\\Yellow_Glow.blp" );
				Preload( "units\\human\\ArthaswithSword\\ArthaswithSword_portrait.mdx" );
				Preload( "Textures\\Arthas.blp" );
				Preload( "units\\undead\\HeroLich\\HeroLich_portrait.mdx" );
				Preload( "Textures\\HeroLich.blp" );
				Preload( "units\\orc\\Grunt\\Grunt.mdx" );
				Preload( "units\\Orc\\Grunt\\Grunt.blp" );
				Preload( "Textures\\Shockwave_Ice1.blp" );
				Preload( "units\\orc\\Grunt\\Grunt_portrait.mdx" );
				Preload( "units\\orc\\WolfRider\\WolfRider.mdx" );
				Preload( "units\\Orc\\Wolfrider\\Wolfrider.blp" );
				Preload( "units\\orc\\WolfRider\\WolfRider_portrait.mdx" );
				Preload( "units\\nightelf\\DruidoftheTalon\\DruidoftheTalon_portrait.mdx" );
				Preload( "units\\NightElf\\DruidOfTheTalon\\DruidottheTalon.blp" );
				Preload( "units\\NightElf\\DruidOfTheTalon\\Raven.blp" );
				Preload( "units\\orc\\Tauren\\Tauren.mdx" );
				Preload( "units\\Orc\\Tauren\\Minotaur.blp" );
				Preload( "Textures\\Zap1.blp" );
				Preload( "units\\orc\\Tauren\\Tauren_portrait.mdx" );
				Preload( "units\\creeps\\Murloc\\Murloc_portrait.mdx" );
				Preload( "units\\Creeps\\Murloc\\Murloc.blp" );
				Preload( "units\\orc\\KotoBeast\\KotoBeast_portrait.mdx" );
				Preload( "Textures\\KotoBeast.blp" );
				Preload( "units\\orc\\HeadHunter\\HeadHunter.mdx" );
				Preload( "Textures\\Headhunter.blp" );
				Preload( "units\\Orc\\HeadHunter\\OrcBloodTailParticle0.blp" );
				Preload( "units\\Orc\\HeadHunter\\OrcBloodTailParticle3.blp" );
				Preload( "units\\Orc\\HeadHunter\\OrcBloodTailParticle1.blp" );
				Preload( "units\\Orc\\HeadHunter\\OrcBloodTailParticle2.blp" );
				Preload( "units\\orc\\HeadHunter\\HeadHunter_portrait.mdx" );
				Preload( "units\\orc\\Catapult\\Catapult.mdx" );
				Preload( "Textures\\CloudSingle.blp" );
				Preload( "Textures\\Catapult.blp" );
				Preload( "units\\orc\\KotoBeast\\KotoBeast.mdx" );
				Preload( "Abilities\\Spells\\Orc\\WarDrums\\DrumsCasterHeal.mdx" );
				Preload( "Textures\\Shockwave4.blp" );
				Preload( "Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdx" );
				Preload( "units\\undead\\Shade\\Shade_portrait.mdx" );
				Preload( "Textures\\Shade.blp" );
				Preload( "Textures\\GenericGlowX_Mod2.blp" );
				Preload( "units\\orc\\Peon\\Peon.mdx" );
				Preload( "units\\Orc\\Peon\\peon.blp" );
				Preload( "units\\orc\\Peon\\Peon_portrait.mdx" );
				Preload( "units\\orc\\Shaman\\Shaman.mdx" );
				Preload( "units\\Orc\\Shaman\\Shaman.blp" );
				Preload( "Textures\\Star8b.blp" );
				Preload( "units\\orc\\Shaman\\Shaman_portrait.mdx" );
				Preload( "units\\orc\\WitchDoctor\\WitchDoctor.mdx" );
				Preload( "units\\Orc\\WitchDoctor\\WitchDoctor.blp" );
				Preload( "Textures\\LightningBall.blp" );
				Preload( "units\\orc\\WitchDoctor\\WitchDoctor_portrait.mdx" );
				Preload( "units\\orc\\HeroFarSeer\\HeroFarSeer_portrait.mdx" );
				Preload( "units\\Orc\\HeroFarseer\\HeroFarseer.blp" );
				Preload( "units\\undead\\Ghoul\\Ghoul.mdx" );
				Preload( "units\\Undead\\Ghoul\\Ghoul.blp" );
				Preload( "units\\undead\\Ghoul\\Ghoul_portrait.mdx" );
				Preload( "units\\creeps\\Medivh\\Medivh_portrait.mdx" );
				Preload( "units\\Creeps\\Medivh\\Medivh.blp" );
				Preload( "units\\undead\\Acolyte\\Acolyte.mdx" );
				Preload( "Textures\\Acolyte.blp" );
				Preload( "Textures\\Green_Star.blp" );
				Preload( "Textures\\DemonRune3.blp" );
				Preload( "units\\undead\\Acolyte\\Acolyte_portrait.mdx" );
				Preload( "units\\undead\\MeatWagon\\MeatWagon.mdx" );
				Preload( "Textures\\Meatwagon.blp" );
				Preload( "units\\undead\\MeatWagon\\MeatWagon_portrait.mdx" );
				Preload( "units\\human\\Gyrocopter\\Gyrocopter_portrait.mdx" );
				Preload( "Textures\\gyrocopter.blp" );
				Preload( "units\\Human\\GyroCopter\\CopterBladeBlur.blp" );
				Preload( "units\\undead\\Necromancer\\Necromancer.mdx" );
				Preload( "units\\Undead\\Necromancer\\Necromancer.blp" );
				Preload( "units\\undead\\Necromancer\\Necromancer_portrait.mdx" );
				Preload( "ReplaceableTextures\\TeamGlow\\TeamGlow04.blp" );
				Preload( "units\\nightelf\\HeroDemonHunter\\HeroDemonHunter_portrait.mdx" );
				Preload( "Textures\\HeroDemonHunter.blp" );
				Preload( "Textures\\Black32.blp" );
				Preload( "units\\undead\\CryptFiend\\CryptFiend.mdx" );
				Preload( "Textures\\CryptFiend.blp" );
				Preload( "units\\undead\\CryptFiend\\CryptFiend_portrait.mdx" );
				Preload( "units\\undead\\Abomination\\Abomination.mdx" );
				Preload( "Textures\\Abomination.blp" );
				Preload( "Textures\\BloodSplash.blp" );
				Preload( "Textures\\BloodSput.blp" );
				Preload( "Textures\\OrcBloodTailParticle.blp" );
				Preload( "units\\undead\\Abomination\\Abomination_portrait.mdx" );
				Preload( "units\\nightelf\\Wisp\\Wisp_portrait.mdx" );
				Preload( "units\\NightElf\\Wisp\\Wisp.blp" );
				PreloadEnd( 5.0 );
			}

		} // class CreditsTeam1_pld 

	}

