// Generated by .

	public partial class GameDefine 
	{

		public class CreditsLegal_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "buildings\\undead\\Necropolis\\Necropolis.mdx" );
				Preload( "Textures\\GraveYardGhost.blp" );
				Preload( "buildings\\Undead\\Necropolis\\CreepyNecropolis.blp" );
				Preload( "buildings\\human\\ArcaneSanctum\\ArcaneSanctum.mdx" );
				Preload( "Textures\\DeathSmug.blp" );
				Preload( "buildings\\Human\\ArcaneSanctum\\ArcaneSanctum.blp" );
				Preload( "Textures\\Purple_Star.blp" );
				Preload( "Textures\\HumanBase.blp" );
				Preload( "buildings\\orc\\SpiritLodge\\SpiritLodge.mdx" );
				Preload( "buildings\\Orc\\SpiritLodge\\SpiritLodge.blp" );
				Preload( "Textures\\OrcBirth.blp" );
				Preload( "buildings\\nightelf\\ChimaeraRoost\\ChimaeraRoost.mdx" );
				Preload( "buildings\\NightElf\\ChimaeraRoost\\ChimaeraRoost.blp" );
				Preload( "Textures\\NightElfBase.blp" );
				Preload( "Textures\\star32.blp" );
				Preload( "Textures\\GenericGlow1.blp" );
				Preload( "Textures\\lensflare1A.blp" );
				Preload( "SharedModels\\NEBirth.mdx" );
				Preload( "SharedModels\\NightElfBirth2.blp" );
				Preload( "Textures\\rainTail.blp" );
				Preload( "Textures\\RibbonNE1_blue.blp" );
				Preload( "Textures\\Star7b.blp" );
				Preload( "Textures\\star4_32.blp" );
				Preload( "Textures\\grad2d.blp" );
				Preload( "SharedModels\\RootsBuild.blp" );
				Preload( "buildings\\human\\TownHall\\TownHall.mdx" );
				Preload( "buildings\\Human\\TownHall\\TownHallCastleKeep.blp" );
				Preload( "Textures\\Shockwave1.blp" );
				Preload( "Textures\\Clouds8x8Mod.blp" );
				Preload( "ReplaceableTextures\\Splats\\HumanTownHallUberSplat.blp" );
				Preload( "ReplaceableTextures\\Splats\\HumanCastleUberSplat.blp" );
				Preload( "buildings\\other\\SacrificialAltar\\SacrificialAltar.mdx" );
				Preload( "buildings\\Other\\SacrificialAltar\\SacrificialAltar.blp" );
				Preload( "Textures\\Red_Glow3.blp" );
				Preload( "units\\critters\\FlyingSheep\\FlyingSheep_portrait.mdx" );
				Preload( "units\\Critters\\FlyingSheep\\SheepA.blp" );
				PreloadEnd( 0.0 );
			}

		} // class CreditsLegal_pld 

	}

