// Generated by .


	public partial class GameDefine 
	{

		public class CreditsBlizzard_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "buildings\\other\\GoldMine\\GoldMine.mdx" );
				Preload( "Textures\\Goldmine.blp" );
				Preload( "Textures\\Chest.blp" );
				Preload( "Textures\\Dust3.blp" );
				Preload( "Textures\\Base.blp" );
				Preload( "ReplaceableTextures\\Splats\\GoldmineUberSplat.blp" );
				Preload( "Textures\\star5tga.blp" );
				Preload( "units\\human\\Knight\\Knight.mdx" );
				Preload( "Textures\\Dust3x.blp" );
				Preload( "Textures\\Knight.blp" );
				Preload( "units\\human\\Knight\\Knight_portrait.mdx" );
				Preload( "units\\nightelf\\Furion\\Furion_portrait.mdx" );
				Preload( "units\\NightElf\\Furion\\Furion.blp" );
				PreloadEnd( 1.0 );
			}

		} // class CreditsBlizzard_pld 

	}

