// Generated by .

	public partial class GameDefine 
	{

		public class h01x05_ai
		{
		//============================================================================
		//  $Id: h01x05.ai,v 1.8 2003/04/29 00:26:32 rpardo Exp $
		//============================================================================
			public BJPlayer  user = PlayerEx(1);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetReplacements(2,2,3);
				campaign_wood_peons = 2;
				SetBuildUnitEx( 1, 1, 1, ACOLYTE );
				SetBuildUnitEx( 0, 0, 1, NECROPOLIS_1 );
				SetBuildUnitEx( 0, 0, 1, CRYPT );
				SetBuildUnitEx( 0, 0, 5, ZIGGURAT_1 );
				SetBuildUnitEx( 0, 0, 1, GRAVEYARD );
				SetBuildUnitEx( 0, 0, 1, UNDEAD_ALTAR );
				SetBuildUnitEx( 0, 0, 1, NECROPOLIS_2 );
				SetBuildUnitEx( 0, 0, 1, DAMNED_TEMPLE );
				SetBuildUnitEx( 0, 0, 4, ZIGGURAT_2 );
				SetBuildUnitEx( 2, 2, 2, UNDEAD_BARGE );
				SetBuildUnitEx( 5, 5, 5, ACOLYTE );
				CampaignDefenderEx( 1, 1, 1, GHOUL );
				CampaignDefenderEx( 1, 1, 1, BANSHEE );
				CampaignDefenderEx( 1, 1, 1, NECRO );
				SetBuildUpgrEx( 1,1,1, UPG_FIEND_WEB );
				SetBuildUpgrEx( 0,0,1, UPG_NECROS );
				SetBuildUpgrEx( 0,0,1, UPG_BANSHEE );
				SetBuildUpgrEx( 1,1,1, UPG_SKEL_LIFE );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,4, GHOUL );
				CampaignAttackerEx( 2,2,4, BANSHEE );
				SuicideOnPlayerEx(M3,M3,M2,user);
				SetBuildUpgrEx( 0,0,1, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 0,1,1, UPG_CR_ATTACK );
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, CRYPT_FIEND );
				CampaignAttackerEx( 2,2,4, NECRO );
				SuicideOnPlayerEx(M5,M5,M3,user);
				SetBuildUpgrEx( 0,0,1, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 0,0,1, UPG_CR_ARMOR );
				SetBuildUpgrEx( 1,1,1, UPG_NECROS );
				SetBuildUpgrEx( 1,1,1, UPG_BANSHEE );
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,5, GHOUL );
				CampaignAttackerEx( 3,3,5, BANSHEE );
				SuicideOnPlayerEx(M5,M5,M3,user);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,5, GHOUL );
				CampaignAttackerEx( 2,2,4, CRYPT_FIEND );
				CampaignAttackerEx( 1,1,2, BANSHEE );
				SuicideOnPlayerEx(M5,M5,M3,user);
				SetBuildUpgrEx( 1,1,2, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 1,1,2, UPG_CR_ATTACK );
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,5, GHOUL );
				CampaignAttackerEx( 1,1,2, MEAT_WAGON );
				CampaignAttackerEx( 2,2,3, NECRO );
				SuicideOnPlayerEx(M5,M5,M3,user);
				SetBuildUpgrEx( 1,1,2, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 1,1,2, UPG_CR_ARMOR );
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttackerEx( 5,5,7, GHOUL );
				CampaignAttackerEx( 3,3,4, BANSHEE );
				SuicideOnPlayerEx(M5,M5,M3,user);
				//*** WAVE 7+ ***
				while( true )
				{
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,5, NECRO );
					CampaignAttackerEx( 3,3,4, CRYPT_FIEND );
					CampaignAttackerEx( 1,1,2, MEAT_WAGON );
					SuicideOnPlayerEx(M5,M5,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,7, GHOUL );
					CampaignAttackerEx( 3,3,4, BANSHEE );
					SuicideOnPlayerEx(M5,M5,M3,user);
					InitAssaultGroup();
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,5, GHOUL );
					CampaignAttackerEx( 2,2,4, CRYPT_FIEND );
					CampaignAttackerEx( 2,2,3, BANSHEE );
					CampaignAttackerEx( 1,1,2, NECRO );
					SuicideOnPlayerEx(M5,M5,M3,user);
				}
			}

		} // class h01x05_ai 

	}

