// Generated by .

	public partial class GameDefine 
	{

		public class h02_red_ai
		{
		//============================================================================
		//  Human 02 -- red player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(1);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(PIG_FARM,null);
				SetReplacements(0,1,3);
				CampaignDefenderEx( 1,1,1, HEAD_HUNTER );
				CampaignDefenderEx( 1,1,2, GRUNT );
				CampaignDefenderEx( 0,0,1, RAIDER );
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,2, GRUNT );
				CampaignAttackerEx( 1,1,2, HEAD_HUNTER );
				SuicideOnPlayer(M2,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,2, GRUNT );
				CampaignAttackerEx( 2,2,3, HEAD_HUNTER );
				SuicideOnPlayer(M2,user);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,4, GRUNT );
				CampaignAttackerEx( 0,0,2, RAIDER );
				CampaignAttackerEx( 1,1,1, HEAD_HUNTER );
				SuicideOnPlayer(M3,user);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,3, GRUNT );
				CampaignAttackerEx( 1,1,3, HEAD_HUNTER );
				SuicideOnPlayer(M2,user);
				while( true )
				{
					//*** WAVE 5 ***
					InitAssaultGroup();
					CampaignAttackerEx( 1,1,3, GRUNT );
					CampaignAttackerEx( 0,0,2, RAIDER );
					CampaignAttackerEx( 4,4,4, HEAD_HUNTER );
					SuicideOnPlayer(M3,user);
					//*** WAVE 6 ***
					InitAssaultGroup();
					CampaignAttackerEx( 4,4,5, GRUNT );
					CampaignAttackerEx( 1,1,2, HEAD_HUNTER );
					SuicideOnPlayer(M3,user);
					//*** WAVE 7 ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,3, GRUNT );
					CampaignAttackerEx( 0,0,2, RAIDER );
					CampaignAttackerEx( 3,3,4, HEAD_HUNTER );
					SuicideOnPlayer(M4,user);
				}
			}

		} // class h02_red_ai 

	}

