// Generated by .

	public partial class GameDefine 
	{

		public class h02x05_ai
		{
		//==================================================================================================
		//  $Id: h02x05.ai,v 1.16.2.1 2003/05/09 09:17:04 abond Exp $
		//==================================================================================================
			public BJPlayer  user = PlayerEx(1);
		//--------------------------------------------------------------------------------------------------
		//  main
		//--------------------------------------------------------------------------------------------------
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetHarvestLumber(false);
				DoCampaignFarms(false);
				SetBuildUnitEx( 1,1,1, ACOLYTE );
				SetBuildUnitEx( 1,1,1, UNDEAD_MINE );
				SetBuildUnitEx( 1,1,1, NECROPOLIS_1 );
				SetBuildUnitEx( 5,5,5, ACOLYTE );
				while( true )
				{
					if(  TownCountDone(NECROPOLIS_1) > 0 )
						break;
					Sleep(1);
				}
				ResetCaptainLocs();
				SetHarvestLumber(true);
				SetWoodPeons(2);
				InitBuildArray();
				SetBuildUnitEx( 0,0,2, UNDEAD_BARGE );
				SetBuildUnitEx( 5,5,5, ACOLYTE );
				CampaignDefenderEx( 1,1,1, GHOUL );
				CampaignDefenderEx( 0,0,1, CRYPT_FIEND );
				CampaignDefenderEx( 1,1,1, NECRO );
				CampaignDefenderEx( 0,0,1, ABOMINATION );
				CampaignDefenderEx( 1,1,1, OBS_STATUE );
				CampaignDefenderEx( 1,1,1, BLK_SPHINX );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, CRYPT_FIEND );
				SuicideOnPlayerEx(M1,M1,M1,user);
				SetBuildUpgrEx( 0,0,1, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 0,0,1, UPG_CR_ATTACK );
				SetBuildUpgrEx( 0,0,1, UPG_SKEL_LIFE );
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 6,6,7, GHOUL );
				CampaignAttackerEx( 2,2,3, BANSHEE );
				CampaignAttackerEx( 1,1,1, MEAT_WAGON );
				SuicideOnPlayerEx(M6,M6,M4,user);
				SetBuildUpgrEx( 0,0,1, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 0,0,1, UPG_CR_ARMOR );
				SetBuildUpgrEx( 1,1,2, UPG_NECROS );
				SetBuildUpgrEx( 1,1,2, UPG_BANSHEE );
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,0, GHOUL );
				CampaignAttackerEx( 2,2,4, CRYPT_FIEND );
				CampaignAttackerEx( 3,3,4, NECRO );
				CampaignAttackerEx( 0,0,3, ABOMINATION );
				CampaignAttackerEx( 0,0,1, MEAT_WAGON );
				SuicideOnPlayerEx(M6,M6,M4,user);
				SetBuildUpgrEx( 0,0,1, UPG_PLAGUE );
				SetBuildUpgrEx( 1,1,2, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 1,1,2, UPG_CR_ATTACK );
				SetBuildUpgrEx( 0,0,1, UPG_SKEL_MASTERY );
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,3, BANSHEE );
				CampaignAttackerEx( 5,5,7, CRYPT_FIEND );
				CampaignAttackerEx( 1,1,2, MEAT_WAGON );
				SuicideOnPlayerEx(M6,M6,M4,user);
				SetBuildUpgrEx( 1,1,2, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 1,1,2, UPG_CR_ARMOR );
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,5, GHOUL );
				CampaignAttackerEx( 0,0,2, CRYPT_FIEND );
				CampaignAttackerEx( 5,5,7, NECRO );
				CampaignAttackerEx( 0,0,1, MEAT_WAGON );
				SuicideOnPlayerEx(M6,M6,M4,user);
				SetBuildUpgrEx( 1,1,3, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 1,1,3, UPG_CR_ATTACK );
				SetBuildUpgrEx( 0,0,1, UPG_GHOUL_FRENZY);
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, BANSHEE );
				CampaignAttackerEx( 0,0,3, ABOMINATION );
				CampaignAttackerEx( 4,4,6, CRYPT_FIEND );
				CampaignAttackerEx( 1,1,2, MEAT_WAGON );
				SuicideOnPlayerEx(M6,M6,M4,user);
				SetBuildUpgrEx( 1,1,3, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 1,1,3, UPG_CR_ARMOR );
				SetBuildUpgrEx( 1,1,2, UPG_NECROS );
				SetBuildUpgrEx( 1,1,2, UPG_BANSHEE );
				//*** WAVE 7+ ***
				while( true )
				{
					InitAssaultGroup();
					CampaignAttackerEx( 0,0,3, ABOMINATION );
					CampaignAttackerEx( 5,5,0, GHOUL );
					CampaignAttackerEx( 2,2,3, CRYPT_FIEND );
					CampaignAttackerEx( 4,4,6, NECRO );
					CampaignAttackerEx( 1,1,2, MEAT_WAGON );
					SuicideOnPlayerEx(M6,M6,M4,user);
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, CRYPT_FIEND );
					CampaignAttackerEx( 3,3,4, NECRO );
					CampaignAttackerEx( 3,3,4, BANSHEE );
					CampaignAttackerEx( 0,0,1, MEAT_WAGON );
					SuicideOnPlayerEx(M6,M6,M4,user);
					InitAssaultGroup();
					CampaignAttackerEx( 6,6,0, GHOUL );
					CampaignAttackerEx( 3,3,5, BANSHEE );
					CampaignAttackerEx( 0,0,3, ABOMINATION );
					CampaignAttackerEx( 1,1,2, MEAT_WAGON );
					SuicideOnPlayerEx(M6,M6,M4,user);
				}
			}

		} // class h02x05_ai 

	}

