// Generated by .


	public partial class GameDefine 
	{

		public class h04_orange_ai
		{
		//============================================================================
		//  Human 04 -- orange player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(1);
			public void do_cheats(  )
			{
				// Original JassCode
				Cheat("showmap");
				Cheat("av");
				Cheat("dg");
				Cheat("warnings");
				Cheat("viewres");
				//    call Cheat("superspeed")
				debug_fast_attacks = true;
			}

		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				do_cheats();
				campaign_wood_peons = 1;
				CampaignAI(ZIGGURAT_1,null);
				SetBuildUnit( 3, ACOLYTE );
				SetBuildUnit( 1, NECROPOLIS_1 );
				SetBuildUnit( 1, UNDEAD_MINE );
				SetBuildUnit( 1, ZIGGURAT_1 );
				SetBuildUnit( 1, ZIGGURAT_2 );
				SetBuildUnit( 1, CRYPT );
				CampaignDefender (EASY, 2, GHOUL );
				//    call SleepForever()
			}

		} // class h04_orange_ai 

	}

