// Generated by .


	public partial class GameDefine 
	{

		public class h04x10_ai
		{
		//==================================================================================================
		//  $Id: h04x10.ai,v 1.7 2003/04/20 22:10:55 smercer Exp $
		//==================================================================================================
			public int USER = 1;
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SuicideUnitsEx( USER, NAGA_MYRMIDON, NAGA_SIREN, NAGA_DRAGON, HIGH_SWORDMAN, HIGH_ARCHER, SORCERESS, PRIEST, SPELL_BREAKER, UnitId( "ncfs" ), NAGA_ROYAL);
			}

		} // class h04x10_ai 

	}

