// Generated by .


	public partial class GameDefine 
	{

		public class h04x11_ai
		{
		//============================================================================

		//  $Id: h04x11.ai,v 1.5 2003/04/20 22:10:55 smercer Exp $

		//============================================================================

			public int USER = 7;
			public void main(  )
			{
				// Original JassCode
				CampaignAI(MOON_WELL,null);
				SuicideUnitsEx( USER, HUNTRESS, ARCHER, DRUID_CLAW, DRUID_CLAW_M, DRUID_TALON, DRYAD, MOUNTAIN_GIANT, UnitId( "espv" ), UnitId( "even" ), 0);
			}

		} // class h04x11_ai 

	}

