// Generated by .


	public partial class GameDefine 
	{

		public class h05_orange_ai
		{
		//============================================================================
		//  Human 05 -- orange player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(1);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				do_campaign_farms = false;
				CampaignAI(ZIGGURAT_1,null);
				SetCaptainHome(ATTACK_CAPTAIN,6235,2786);
				SetCaptainHome(DEFENSE_CAPTAIN,5021,2735);
				SetBuildUnit( 1,NECROPOLIS_1 );
				SetBuildUnit( 1,ACOLYTE );
				SetBuildUnit( 2,ZIGGURAT_1 );
				SetBuildUnit( 1,UNDEAD_MINE );
				SetBuildUnit( 1,UNDEAD_ALTAR );
				SetBuildUnit( 1,GRAVEYARD );
				SetBuildUnit( 2,CRYPT );
				SetBuildUnit( 5,ACOLYTE );
				SetBuildUnit( 8,ZIGGURAT_1 );
				SetBuildUnit( 1,NECROPOLIS_2 );
				SetBuildUnit( 1,SAC_PIT );
				SetBuildUnit( 1,DAMNED_TEMPLE );
				SetBuildUnit( 1,SLAUGHTERHOUSE );
				SetBuildUnit( 8,ZIGGURAT_2 );
				SetBuildUnit( 1,NECROPOLIS_3 );
				CampaignDefenderEx( 9,9,9, GHOUL );
				CampaignDefenderEx( 2,4,6, NECRO );
				CampaignDefenderEx( 2,3,4, ABOMINATION );
				CampaignDefenderEx( 2,3,4, MEAT_WAGON );
				WaitForSignal();
				allow_signal_abort = true;
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, GHOUL );
				SuicideOnPlayer(M3,user);
				ForeverSuicideOnPlayer(M2,user);
				SuicideUnits( MEAT_WAGON, ABOMINATION, GHOUL, NECRO, SKEL_WARRIOR, LICH, 0, 0, 0, 0 );
			}

		} // class h05_orange_ai 

	}

