// Generated by .

	public partial class GameDefine 
	{

		public class h05x07_ai
		{
		//==================================================================================================
		//  $Id: h05x07.ai,v 1.15 2003/05/05 12:04:17 bfitch Exp $
		//==================================================================================================
			public BJPlayer  targ1 = PlayerEx(6);
			public BJPlayer  targ2 = PlayerEx(4);
			public BJPlayer  targ = PlayerEx(6);
			// hero
			public int AKAMA = UnitId( "Naka" );
			public int DPEON = UnitId( "ndrl" );
			public int DCATAPULT = UnitId( "ncat" );
			// lvl 4, ranged
			public int DSALAMANDER = UnitId( "ndsa" );
			// lvl 5, assassin unit
			public int DSTALKER = UnitId( "ndrt" );
			// lvl 5, heavy melee
			public int DVINDICATOR = UnitId( "ndrn" );
			// lvl 4, bloodlust, dispel
			public int DHARBINGER = UnitId( "ndrh" );
			// lvl 6, healwave, brilliance,slow
			public int DSEER = UnitId( "ndrs" );
		//--------------------------------------------------------------------------------------------------
		//  switch_targets
		//--------------------------------------------------------------------------------------------------
			public void switch_targets(  )
			{
				// Original JassCode
				while( true )
				{
					if(  CommandsWaiting() > 0 )
						break;
					Sleep(1);
				}
				targ = targ2;
			}

		//--------------------------------------------------------------------------------------------------
		//  main
		//--------------------------------------------------------------------------------------------------
			public void main(  )
			{
				// Original JassCode
				CampaignAI(PIG_FARM,null);
				DoCampaignFarms(false);
				SetReplacements(9,9,9);
				SetPeonsRepair(true);
				SetCaptainHome(ATTACK_CAPTAIN, -4268,-6436);
				SetCaptainHome(DEFENSE_CAPTAIN,-4723,-6604);
				SetBuildUnitEx( 3,3,3, DPEON );
				CampaignDefenderEx( 1, 1, 1, DVINDICATOR );
				CampaignDefenderEx( 1, 1, 1, DSEER );
				CampaignDefenderEx( 1, 1, 1, DSALAMANDER );
				CampaignDefenderEx( 1, 1, 1, AKAMA );
				WaitForSignal();
				StartThread( switch_targets);
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,2, DVINDICATOR );
				CampaignAttackerEx( 4,4,3, DSALAMANDER );
				CampaignAttackerEx( 1,1,1, AKAMA );
				SuicideOnPlayerEx(M1,M1,M1,targ);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 8,8,6, DSTALKER );
				SuicideOnPlayerEx(M4,M4,M4,targ);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,2, DVINDICATOR );
				CampaignAttackerEx( 2,2,1, DHARBINGER );
				CampaignAttackerEx( 2,2,1, DCATAPULT );
				CampaignAttackerEx( 1,1,1, AKAMA );
				SuicideOnPlayerEx(M4,M4,M4,targ);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,2, DVINDICATOR );
				CampaignAttackerEx( 2,2,1, DHARBINGER );
				CampaignAttackerEx( 2,2,1, DCATAPULT );
				SuicideOnPlayerEx(M4,M4,M4,targ);
				while( true )
				{
					//*** WAVE 5 ***
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,4, DVINDICATOR );
					CampaignAttackerEx( 2,2,2, DSALAMANDER );
					CampaignAttackerEx( 1,1,1, DSEER );
					CampaignAttackerEx( 1,1,1, DCATAPULT );
					SuicideOnPlayerEx(M4,M4,M4,targ);
					//*** WAVE 6 ***
					InitAssaultGroup();
					CampaignAttackerEx( 9,9,7, DSTALKER );
					CampaignAttackerEx( 1,1,1, AKAMA );
					SuicideOnPlayerEx(M4,M4,M4,targ);
					//*** WAVE 7 ***
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,4, DVINDICATOR );
					CampaignAttackerEx( 2,2,2, DSALAMANDER );
					CampaignAttackerEx( 1,1,1, DSEER );
					CampaignAttackerEx( 1,1,1, DCATAPULT );
					SuicideOnPlayerEx(M4,M4,M4,targ);
					//*** WAVE 8 ***
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,4, DVINDICATOR );
					CampaignAttackerEx( 2,2,2, DSALAMANDER );
					CampaignAttackerEx( 1,1,1, DHARBINGER );
					CampaignAttackerEx( 1,1,1, DCATAPULT );
					SuicideOnPlayerEx(M4,M4,M4,targ);
					//*** WAVE 9 ***
					InitAssaultGroup();
					CampaignAttackerEx( 8,8,7, DSTALKER );
					CampaignAttackerEx( 1,1,1, AKAMA );
					SuicideOnPlayerEx(M4,M4,M4,targ);
					//*** WAVE 10 ***
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,4, DVINDICATOR );
					CampaignAttackerEx( 2,2,2, DSALAMANDER );
					CampaignAttackerEx( 1,1,1, DSEER );
					CampaignAttackerEx( 1,1,1, DCATAPULT );
					SuicideOnPlayerEx(M4,M4,M4,targ);
				}
			}

		} // class h05x07_ai 

	}

