// Generated by .


	public partial class GameDefine 
	{

		public class h05x06_ai
		{
		//==================================================================================================
		//  $Id: h05x06.ai,v 1.8 2003/05/04 14:29:07 rpardo Exp $
		//==================================================================================================
			public BJPlayer  user = PlayerEx(1);
			public BJPlayer  akama = PlayerEx(7);
			public BJPlayer  targ = PlayerEx(1);
		//--------------------------------------------------------------------------------------------------
		//  test_quest
		//--------------------------------------------------------------------------------------------------
			public void switch_to_akama(  )
			{
				// Original JassCode
				while( true )
				{
					if(  CommandsWaiting() > 0 )
						break;
					Sleep(1);
				}
				targ = akama;
				SetRandomPaths(false);
				SetBuildUpgrEx( 1,1,1, UPG_ORC_WAR_DRUMS );
				SetBuildUpgrEx( 1,1,1, UPG_ORC_BERSERK );
				SetBuildUpgrEx( 2,2,3, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 2,2,3, UPG_ORC_MELEE );
			}

		//--------------------------------------------------------------------------------------------------
		//  main
		//--------------------------------------------------------------------------------------------------
			public void main(  )
			{
				// Original JassCode
				CampaignAI(CHAOS_BURROW,null);
				SetReplacements(1,1,3);
				DoCampaignFarms(false);
				SetBuildUnitEx( 0,0,1, GREAT_HALL );
				SetBuildUnitEx( 1,1,1, CHAOS_PEON );
				SetBuildUnitEx( 0,0,2, ORC_BARRACKS );
				SetBuildUnitEx( 0,0,5, CHAOS_BURROW );
				SetBuildUnitEx( 0,0,1, FORGE );
				SetBuildUnitEx( 8,8,8, CHAOS_PEON );
				SetBuildUnitEx( 0,0,1, STRONGHOLD );
				SetBuildUnitEx( 0,0,2, BESTIARY );
				SetBuildUnitEx( 0,0,2, LODGE );
				CampaignDefenderEx( 1,1,2, CHAOS_GRUNT );
				CampaignDefenderEx( 0,0,2, CHAOS_WARLOCK );
				CampaignDefenderEx( 1,1,1, CHAOS_RAIDER );
				CampaignDefenderEx( 0,0,1, CHAOS_BLADEMASTER );
				CampaignDefenderEx( 0,0,2, ORC_DRAGON );
				SetBuildUpgrEx( 1,1,1, UPG_ORC_BURROWS );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_MELEE );
				SetBuildUpgrEx( 1,1,1, UPG_ORC_ENSNARE );
				SetBuildUpgrEx( 3,3,3, UPG_ORC_SPIKES );
				WaitForSignal();
				StartThread( switch_to_akama);
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, CHAOS_GRUNT );
				SuicideOnPlayer(M2,targ);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,5, CHAOS_GRUNT );
				CampaignAttackerEx( 2,2,3, CHAOS_RAIDER );
				SuicideOnPlayerEx(M6,M6,M5,targ);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,4, CHAOS_GRUNT );
				CampaignAttackerEx( 1,1,2, CHAOS_RAIDER );
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M7,M7,M6,targ);
				SetBuildUpgrEx( 0,0,1, UPG_ORC_BERSERK );
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, CHAOS_GRUNT );
				CampaignAttackerEx( 1,1,1, CHAOS_KODO );
				CampaignAttackerEx( 1,1,1, CHAOS_BLADEMASTER);
				SuicideOnPlayerEx(M6,M6,M5,targ);
				SetBuildUpgrEx( 0,0,1, UPG_ORC_WAR_DRUMS );
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, CHAOS_RAIDER );
				CampaignAttackerEx( 2,2,3, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M7,M7,M6,targ);
				SetBuildUpgrEx( 1,1,2, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 1,1,2, UPG_ORC_MELEE );
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttackerEx( 6,6,7, CHAOS_GRUNT );
				CampaignAttackerEx( 1,1,1, CHAOS_BLADEMASTER);
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M6,M6,M5,targ);
				//*** WAVE 7 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,7, CHAOS_RAIDER );
				CampaignAttackerEx( 1,1,1, CHAOS_KODO );
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M7,M7,M6,targ);
				SetBuildUpgrEx( 1,1,1, UPG_ORC_WAR_DRUMS );
				//*** WAVE 8 ***
				InitAssaultGroup();
				CampaignAttackerEx( 7,7,9, CHAOS_GRUNT );
				CampaignAttackerEx( 2,2,3, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M6,M6,M5,targ);
				//*** WAVE 9 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,5, CHAOS_GRUNT );
				CampaignAttackerEx( 1,1,1, CHAOS_BLADEMASTER);
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M7,M7,M6,targ);
				SetBuildUpgrEx( 1,1,3, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 1,1,3, UPG_ORC_MELEE );
				//*** WAVE 10 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, CHAOS_GRUNT );
				CampaignAttackerEx( 3,3,4, CHAOS_RAIDER );
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M6,M6,M5,targ);
				while( true )
				{
					//*** WAVE 11 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,5, CHAOS_GRUNT );
					CampaignAttackerEx( 1,1,2, CHAOS_KODO );
					CampaignAttackerEx( 1,1,1, CHAOS_BLADEMASTER);
					CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
					SuicideOnPlayerEx(M7,M7,M6,targ);
					//*** WAVE 12 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, CHAOS_GRUNT );
					CampaignAttackerEx( 3,3,4, CHAOS_RAIDER );
					CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
					SuicideOnPlayerEx(M6,M6,M5,targ);
					//*** WAVE 13 ***
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,8, CHAOS_RAIDER );
					CampaignAttackerEx( 1,1,1, CHAOS_BLADEMASTER);
					SuicideOnPlayerEx(M7,M7,M6,targ);
					//*** WAVE 14+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 6,6,8, CHAOS_GRUNT );
					CampaignAttackerEx( 3,3,4, CHAOS_WARLOCK );
					SuicideOnPlayerEx(M6,M6,M5,targ);
				}
			}

		} // class h05x06_ai 

	}

