// Generated by .

	public partial class GameDefine 
	{

		public class h05x05_ai
		{
		//==================================================================================================
		//  $Id: h05x05.ai,v 1.5 2003/05/04 14:29:07 rpardo Exp $
		//==================================================================================================
			public BJPlayer  user = PlayerEx(7);
		//--------------------------------------------------------------------------------------------------
		//  main
		//--------------------------------------------------------------------------------------------------
			public void main(  )
			{
				// Original JassCode
				CampaignAI(CHAOS_BURROW,null);
				SetReplacements(1,1,3);
				DoCampaignFarms(false);
				SetBuildUnit ( 6, CHAOS_PEON );
				CampaignDefenderEx( 0,0,2, CHAOS_GRUNT );
				CampaignDefenderEx( 1,1,2, CHAOS_WARLOCK );
				CampaignDefenderEx( 1,1,1, CHAOS_RAIDER );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_MELEE );
				SetBuildUpgrEx( 1,1,1, UPG_ORC_BURROWS );
				SetBuildUpgrEx( 1,1,1, UPG_ORC_ENSNARE );
				SetBuildUpgrEx( 3,3,3, UPG_ORC_SPIKES );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,3, CHAOS_GRUNT );
				SuicideOnPlayer(M2,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,3, CHAOS_RAIDER );
				SuicideOnPlayerEx(M1,M1,M1,user);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,2, CHAOS_GRUNT );
				CampaignAttackerEx( 1,1,1, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M1,M1,M1,user);
				while( true )
				{
					//*** WAVE 4 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,3, CHAOS_GRUNT );
					CampaignAttackerEx( 1,1,1, CHAOS_KODO );
					SuicideOnPlayerEx(M1,M1,M1,user);
					//*** WAVE 5 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,3, CHAOS_RAIDER );
					SuicideOnPlayerEx(M1,M1,M1,user);
					//*** WAVE 6 ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,2, CHAOS_GRUNT );
					CampaignAttackerEx( 1,1,1, CHAOS_WARLOCK );
					SuicideOnPlayerEx(M1,M1,M1,user);
					//*** WAVE 7+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,2, CHAOS_GRUNT );
					CampaignAttackerEx( 2,2,2, CHAOS_RAIDER );
					SuicideOnPlayerEx(M1,M1,M1,user);
				}
			}

		} // class h05x05_ai 

	}

