// Generated by .


	public partial class GameDefine 
	{

		public class h06_purple_ai
		{
		//============================================================================
		//  Human 06 -- purple player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(1);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetBuildUnit( 1, NECROPOLIS_1 );
				SetBuildUnit( 1, ACOLYTE );
				SetBuildUnit( 1, UNDEAD_MINE );
				SetBuildUnit( 2, CRYPT );
				SetBuildUnit( 1, UNDEAD_ALTAR );
				SetBuildUnit( 1, GRAVEYARD );
				SetBuildUnit( 8, ZIGGURAT_1 );
				SetBuildUnit( 1, NECROPOLIS_2 );
				SetBuildUnit( 5, ACOLYTE );
				SetBuildUnit( 8, ZIGGURAT_2 );
				SetBuildUnit( 1, DAMNED_TEMPLE );
				SetBuildUnit( 1, SLAUGHTERHOUSE );
				SetBuildUnit( 1, NECROPOLIS_3 );
				CampaignDefender( EASY, 4, GHOUL );
				CampaignDefender( EASY, 2, ABOMINATION );
				CampaignDefender( EASY, 2, NECRO );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 0,0,4, GHOUL );
				SuicideOnPlayerEx(0,0,M2,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,6, GHOUL );
				CampaignAttackerEx( 0,0,1, ABOMINATION );
				SuicideOnPlayerEx(M5,M5,M3,user);
				SetBuildUpgrEx( 1,1,1, UPG_CANNIBALIZE );
				SetBuildUpgrEx( 1,1,1, UPG_UNHOLY_STR );
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,8, GHOUL );
				CampaignAttackerEx( 1,1,2, ABOMINATION );
				CampaignAttackerEx( 0,0,1, MEAT_WAGON );
				SuicideOnPlayerEx(M4,M4,M3,user);
				SetBuildUpgrEx( 1,1,1, UPG_UNHOLY_ARMOR );
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 6,6,10, GHOUL );
				CampaignAttackerEx( 2,2,2, ABOMINATION );
				CampaignAttackerEx( 0,0,1, NECRO );
				SuicideOnPlayerEx(M5,M5,M3,user);
				SetBuildUpgrEx( 1,1,1, UPG_SKEL_LIFE );
				SetBuildUpgrEx( 0,0,2, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 1,1,1, UPG_NECROS );
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,8, GHOUL );
				CampaignAttackerEx( 0,0,2, ABOMINATION );
				CampaignAttackerEx( 2,2,2, NECRO );
				CampaignAttackerEx( 1,1,2, MEAT_WAGON );
				SuicideOnPlayerEx(M4,M4,M3,user);
				SetBuildUpgrEx( 0,0,2, UPG_UNHOLY_ARMOR );
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttackerEx( 10,10,12, GHOUL );
				SuicideOnPlayerEx(M5,M5,M3,user);
				SetBuildUpgrEx( 0,0,1, UPG_PLAGUE );
				SetBuildUpgrEx( 0,0,2, UPG_NECROS );
				//*** WAVE 7 ***
				InitAssaultGroup();
				CampaignAttackerEx( 0,0,6, GHOUL );
				CampaignAttackerEx( 4,4,2, ABOMINATION );
				CampaignAttackerEx( 0,0,2, NECRO );
				CampaignAttackerEx( 1,1,2, MEAT_WAGON );
				SuicideOnPlayerEx(M4,M4,M3,user);
				SetBuildUpgrEx( 0,0,1, UPG_GHOUL_FRENZY );
				while( true )
				{
					//*** WAVE 8+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 6,6,6, GHOUL );
					CampaignAttackerEx( 0,0,1, ABOMINATION );
					CampaignAttackerEx( 2,2,3, NECRO );
					SuicideOnPlayerEx(M4,M4,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 4,4,6, GHOUL );
					CampaignAttackerEx( 2,2,3, ABOMINATION );
					CampaignAttackerEx( 1,1,2, MEAT_WAGON );
					SuicideOnPlayerEx(M4,M4,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, NECRO );
					CampaignAttackerEx( 6,6,8, GHOUL );
					SuicideOnPlayerEx(M4,M4,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,6, ABOMINATION );
					CampaignAttackerEx( 2,2,3, MEAT_WAGON );
					CampaignAttackerEx( 0,0,0, GHOUL );
					SuicideOnPlayerEx(M5,M5,M2,user);
				}
			}

		} // class h06_purple_ai 

	}

