// Generated by .

	public partial class GameDefine 
	{

		public class h06x07_ai
		{
		//==================================================================================================
		//  $Id: h06x07.ai,v 1.10 2003/04/30 00:11:41 rpardo Exp $
		//==================================================================================================
			public BJPlayer  user = PlayerEx(1);
			public int NERATHOR = UnitId( "O000" );
			public int ORC_JUGG = UnitId( "ojgn" );
			public int ORC_FRIGATE = UnitId( "odes" );
		//--------------------------------------------------------------------------------------------------
		//  main
		//--------------------------------------------------------------------------------------------------
			public void main(  )
			{
				// Original JassCode
				CampaignAI(BURROW,null);
				SetReplacements(1,1,3);
				campaign_wood_peons = 3;
				SetCaptainHome(BOTH_CAPTAINS,2167,8137);
				CampaignDefenderEx( 1,1,1, CHAOS_GRUNT );
				CampaignDefenderEx( 1,1,1, CHAOS_WARLOCK );
				CampaignDefenderEx( 1,1,1, CHAOS_KODO );
				CampaignDefenderEx( 0,0,1, NERATHOR );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_MELEE );
				SetBuildUpgrEx( 1,1,1, UPG_ORC_SPIKES );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,4, CHAOS_GRUNT );
				CampaignAttackerEx( 0,0,1, NERATHOR );
				SuicideOnUnitsEx(M2,M2,M2,user);
				while( true )
				{
					//*** WAVE 2+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,5, CHAOS_GRUNT );
					CampaignAttackerEx( 1,1,1, CHAOS_KODO );
					CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
					SuicideOnUnitsEx(M5,M5,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, CHAOS_GRUNT );
					CampaignAttackerEx( 1,1,1, NERATHOR );
					CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
					SuicideOnUnitsEx(M5,M5,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,5, CHAOS_GRUNT );
					CampaignAttackerEx( 1,1,1, CHAOS_KODO );
					CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
					SuicideOnUnitsEx(M5,M5,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 6,6,8, CHAOS_GRUNT );
					CampaignAttackerEx( 3,3,4, CHAOS_WARLOCK );
					CampaignAttackerEx( 0,0,1, NERATHOR );
					SuicideOnUnitsEx(M5,M5,M3,user);
				}
			}

		} // class h06x07_ai 

	}

