// Generated by .

	public partial class GameDefine 
	{

		public class h06x05_ai
		{
		//==================================================================================================
		//  $Id: h06x05.ai,v 1.5 2003/04/29 00:19:57 rpardo Exp $
		//==================================================================================================
			public BJPlayer  user = PlayerEx(1);
			public int SAGRANEL = UnitId( "N00A" );
			public int ORC_JUGG = UnitId( "ojgn" );
			public int ORC_FRIGATE = UnitId( "odes" );
		//--------------------------------------------------------------------------------------------------
		//  main
		//--------------------------------------------------------------------------------------------------
			public void main(  )
			{
				// Original JassCode
				CampaignAI(BURROW,null);
				SetReplacements(1,1,3);
				SetCaptainHome(DEFENSE_CAPTAIN,3885,906);
				CampaignDefenderEx( 0,0,1, CHAOS_GRUNT );
				CampaignDefenderEx( 0,0,1, CHAOS_WARLOCK );
				CampaignDefenderEx( 0,0,1, SAGRANEL );
				SleepForever();
			}

		} // class h06x05_ai 

	}

