// Generated by .


	public partial class GameDefine 
	{

		public class h06x08_ai
		{
		//==================================================================================================
		//  $Id: h06x08.ai,v 1.8 2003/04/30 00:11:41 rpardo Exp $
		//==================================================================================================
			public BJPlayer  user = PlayerEx(1);
		//--------------------------------------------------------------------------------------------------
		//  main
		//--------------------------------------------------------------------------------------------------
			public void main(  )
			{
				// Original JassCode
				CampaignAI(BURROW,null);
				SetReplacements(1,1,3);
				campaign_wood_peons = 3;
				SetBuildUnitEx ( 3,3,3, CHAOS_PEON );
				CampaignDefenderEx( 0,0,1, CHAOS_GRUNT );
				CampaignDefenderEx( 1,1,1, CHAOS_WARLOCK );
				CampaignDefenderEx( 1,1,0, CHAOS_RAIDER );
				CampaignDefenderEx( 0,0,1, CHAOS_GROM );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_MELEE );
				SetBuildUpgrEx( 1,1,1, UPG_ORC_SPIKES );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 5,5,6, CHAOS_RAIDER );
				SuicideOnUnitsEx(M2,M2,M2,user);
				while( true )
				{
					//*** WAVE 2+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 4,4,5, CHAOS_RAIDER );
					CampaignAttackerEx( 0,0,1, CHAOS_GROM );
					SuicideOnUnitsEx(M5,M5,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,4, CHAOS_GRUNT );
					CampaignAttackerEx( 3,3,4, CHAOS_RAIDER );
					CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
					SuicideOnUnitsEx(M5,M5,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,5, CHAOS_RAIDER );
					CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
					CampaignAttackerEx( 0,0,1, CHAOS_GROM );
					SuicideOnUnitsEx(M5,M5,M3,user);
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,6, CHAOS_GRUNT );
					CampaignAttackerEx( 2,2,4, CHAOS_WARLOCK );
					CampaignAttackerEx( 1,1,1, CHAOS_KODO );
					SuicideOnUnitsEx(M5,M5,M3,user);
				}
			}

		} // class h06x08_ai 

	}

