// Generated by .


	public partial class GameDefine 
	{

		public class h07_gray_ai
		{
		//============================================================================
		//  Human 07 -- gray player -- AI Script
		//============================================================================
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SetBuildUnit( 1, TOWN_HALL );
				SetBuildUnit( 1, PEASANT );
				SetBuildUnit( 1, BARRACKS );
				SetBuildUnit( 1, BLACKSMITH );
				SetBuildUnit( 1, KEEP );
				SetBuildUnit( 1, WORKSHOP );
				SetBuildUnit( 2, PEASANT );
				SleepForever();
			}

		} // class h07_gray_ai 

	}

