// Generated by .


	public partial class GameDefine 
	{

		public class h09_yellow_ai
		{
		//============================================================================
		//  Orc 05  -- brown player -- AI Script
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SuicideUnits( GHOUL, NECRO, ABOMINATION, GARGOYLE, CRYPT_FIEND, GHOUL, ABOMINATION, NECRO, GARGOYLE, CRYPT_FIEND );
			}

		} // class h09_yellow_ai 

	}

