// Generated by .


	public partial class GameDefine 
	{

		public class h09_teal_ai
		{
		//============================================================================
		//  Human 09 -- teal player -- AI Script
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetReplacements(1,1,3);
				SetBuildUnitEx( 0,0,1, NECROPOLIS_1 );
				SetBuildUnitEx( 1,1,1, ACOLYTE );
				SetBuildUnitEx( 0,0,1, UNDEAD_MINE );
				SetBuildUnitEx( 0,0,1, CRYPT );
				SetBuildUnitEx( 0,0,1, GRAVEYARD );
				SetBuildUnitEx( 0,0,1, UNDEAD_ALTAR );
				SetBuildUnitEx( 0,0,1, NECROPOLIS_2 );
				SetBuildUnitEx( 0,0,1, SLAUGHTERHOUSE );
				SetBuildUnitEx( 0,0,1, SAC_PIT );
				SetBuildUnitEx( 0,0,1, NECROPOLIS_3 );
				SetBuildUnitEx( 0,0,5, ACOLYTE );
				CampaignDefenderEx( 1,1,3, GHOUL );
				CampaignDefenderEx( 1,1,2, ABOMINATION );
				CampaignDefenderEx( 0,0,2, CRYPT_FIEND );
				SleepForever();
			}

		} // class h09_teal_ai 

	}

