// Generated by .


	public partial class GameDefine 
	{

		public class h09_green_ai
		{
		//============================================================================
		//  Human 09 -- green player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(1);
		//============================================================================
		//  after_sword
		//============================================================================
			public void after_sword(  )
			{
				// Original JassCode
				// grab all the upgrades we're ever going to get
				// post-sword, then start a post-sword loop
				//
				SetBuildUpgr ( 1, UPG_FIEND_WEB );
				SetBuildUpgrEx( 1,1,1, UPG_CANNIBALIZE );
				SetBuildUpgrEx( 1,1,1, UPG_SKEL_LIFE );
				SetBuildUpgrEx( 1,1,1, UPG_GHOUL_FRENZY );
				SetBuildUpgrEx( 1,1,1, UPG_STONE_FORM );
				SetBuildUpgrEx( 0,0,1, UPG_PLAGUE );
				SetBuildUpgrEx( 1,1,1, UPG_WYRM_BREATH );
				SetBuildUpgrEx( 2,2,2, UPG_NECROS );
				SetBuildUpgrEx( 0,0,3, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 0,0,3, UPG_UNHOLY_ARMOR );
				SetBuildUpgrEx( 0,0,3, UPG_CR_ATTACK );
				SetBuildUpgrEx( 0,0,3, UPG_CR_ARMOR );
				while( true )
				{
					//*** WAVE 9+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 1,1,1, MALGANIS );
					CampaignAttackerEx( 2,2,5, CRYPT_FIEND );
					CampaignAttackerEx( 0,0,1, ABOMINATION );
					CampaignAttackerEx( 2,2,3, NECRO );
					CampaignAttackerEx( 1,1,4, MEAT_WAGON );
					SuicideOnPlayerEx(M8,M8,M8,user);
					InitAssaultGroup();
					CampaignAttackerEx( 0,0,1, MALGANIS );
					CampaignAttackerEx( 0,0,2, ABOMINATION );
					CampaignAttackerEx( 2,2,8, GARGOYLE );
					CampaignAttackerEx( 2,2,3, FROST_WYRM );
					CampaignAttackerEx( 0,0,1, MEAT_WAGON );
					SuicideOnPlayerEx(M10,M10,M8,user);
					InitAssaultGroup();
					CampaignAttackerEx( 1,1,1, MALGANIS );
					CampaignAttackerEx( 2,2,4, ABOMINATION );
					CampaignAttackerEx( 1,1,3, MEAT_WAGON );
					CampaignAttackerEx( 0,0,4, CRYPT_FIEND );
					CampaignAttackerEx( 0,0,3, NECRO );
					CampaignAttackerEx( 2,2,6, GHOUL );
					SuicideOnPlayerEx(M8,M8,M8,user);
					InitAssaultGroup();
					CampaignAttackerEx( 0,0,1, MALGANIS );
					CampaignAttackerEx( 8,8,8, GARGOYLE );
					CampaignAttackerEx( 1,1,3, FROST_WYRM );
					SuicideOnPlayerEx(M10,M10,M8,user);
				}
			}

		//============================================================================
		//  test_sword
		//============================================================================
			public void test_sword(  )
			{
				// Original JassCode
				if(  CommandsWaiting() > 0  )
				{
					after_sword();
				}
			}

		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetReplacements(1,1,3);
				campaign_wood_peons = 1;
				SetBuildUnitEx( 0,0,1, NECROPOLIS_1 );
				SetBuildUnitEx( 1,1,1, ACOLYTE );
				SetBuildUnitEx( 0,0,1, UNDEAD_MINE );
				SetBuildUnitEx( 0,0,1, GRAVEYARD );
				SetBuildUnitEx( 0,0,8, ZIGGURAT_1 );
				SetBuildUnitEx( 0,0,1, NECROPOLIS_2 );
				SetBuildUnitEx( 0,0,1, CRYPT );
				SetBuildUnitEx( 0,0,1, SLAUGHTERHOUSE );
				SetBuildUnitEx( 0,0,1, DAMNED_TEMPLE );
				SetBuildUnitEx( 0,0,1, NECROPOLIS_3 );
				SetBuildUnitEx( 0,0,1, SLAUGHTERHOUSE );
				SetBuildUnitEx( 0,0,5, ACOLYTE );
				SetBuildUnitEx( 0,0,8, ZIGGURAT_2 );
				CampaignDefenderEx( 0,0,1, ABOMINATION );
				CampaignDefenderEx( 0,0,1, NECRO );
				CampaignDefenderEx( 1,1,1, GHOUL );
				CampaignDefenderEx( 1,1,0, GARGOYLE );
				CampaignDefenderEx( 0,0,1, CRYPT_FIEND );
				CampaignDefenderEx( 0,0,1, MALGANIS );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, GHOUL );
				CampaignAttackerEx( 0,0,3, ABOMINATION );
				CampaignAttackerEx( 1,1,2, NECRO );
				SuicideOnPlayerEx(M8,M8,M7,user);
				test_sword();
				SetBuildUpgr( 1, UPG_FIEND_WEB );
				SetBuildUpgrEx( 1,1,1, UPG_CANNIBALIZE );
				SetBuildUpgrEx( 1,1,1, UPG_UNHOLY_STR );
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,4, GHOUL );
				CampaignAttackerEx( 2,2,4, CRYPT_FIEND );
				CampaignAttackerEx( 2,2,4, GARGOYLE );
				SuicideOnPlayerEx(M10,M10,M7,user);
				test_sword();
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,12, GHOUL );
				CampaignAttackerEx( 1,1,3, NECRO );
				CampaignAttackerEx( 2,2,3, CRYPT_FIEND );
				SuicideOnPlayerEx(M8,M8,M7,user);
				test_sword();
				SetBuildUpgrEx( 1,1,1, UPG_CR_ATTACK );
				SetBuildUpgrEx( 1,1,1, UPG_SKEL_LIFE );
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,2, CRYPT_FIEND );
				CampaignAttackerEx( 1,1,3, ABOMINATION );
				CampaignAttackerEx( 2,2,4, MEAT_WAGON );
				SuicideOnPlayerEx(M10,M10,M7,user);
				test_sword();
				SetBuildUpgrEx( 0,0,1, UPG_PLAGUE );
				SetBuildUpgrEx( 1,1,1, UPG_UNHOLY_ARMOR );
				SetBuildUpgrEx( 1,1,1, UPG_CR_ARMOR );
				SetBuildUpgrEx( 1,1,1, UPG_NECROS );
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 0,0,4, ABOMINATION );
				CampaignAttackerEx( 4,4,6, GARGOYLE );
				CampaignAttackerEx( 0,0,2, MEAT_WAGON );
				SuicideOnPlayerEx(M8,M8,M7,user);
				test_sword();
				SetBuildUpgrEx( 2,2,2, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 2,2,2, UPG_CR_ATTACK );
				SetBuildUpgrEx( 1,1,1, UPG_GHOUL_FRENZY );
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,12, GARGOYLE );
				CampaignAttackerEx( 1,1,2, FROST_WYRM );
				SuicideOnPlayerEx(M10,M10,M7,user);
				test_sword();
				SetBuildUpgrEx( 2,2,2, UPG_UNHOLY_ARMOR );
				SetBuildUpgrEx( 2,2,2, UPG_CR_ARMOR );
				SetBuildUpgrEx( 1,1,1, UPG_STONE_FORM );
				SetBuildUpgrEx( 2,2,2, UPG_NECROS );
				SetBuildUpgrEx( 1,1,1, UPG_WYRM_BREATH );
				while( true )
				{
					//*** WAVE 9+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,5, CRYPT_FIEND );
					CampaignAttackerEx( 0,0,1, ABOMINATION );
					CampaignAttackerEx( 2,2,3, NECRO );
					CampaignAttackerEx( 2,2,4, MEAT_WAGON );
					SuicideOnPlayerEx(M8,M8,M7,user);
					test_sword();
					InitAssaultGroup();
					CampaignAttackerEx( 0,0,2, ABOMINATION );
					CampaignAttackerEx( 3,3,8, GARGOYLE );
					CampaignAttackerEx( 1,1,3, FROST_WYRM );
					CampaignAttackerEx( 0,0,1, MEAT_WAGON );
					SuicideOnPlayerEx(M10,M10,M7,user);
					test_sword();
				}
			}

		} // class h09_green_ai 

	}

