// Generated by .


	public partial class GameDefine 
	{

		public class Human05Interlude_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "ReplaceableTextures\\CameraMasks\\Black_mask.blp" );
				Preload( "Splats\\SplatData.slk" );
				Preload( "ReplaceableTextures\\Splats\\Splat01Mature.blp" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleSmall.blp" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleMed.blp" );
				Preload( "Environment\\Sky\\LordaeronSummerSky\\LordaeronSummerSky.mdx" );
				Preload( "environment\\Sky\\LordaeronSummerSky\\LordaeronSummerSky.blp" );
				Preload( "UI\\TipStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-up.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-down.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-background-disabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-knob.blp" );
				Preload( "UI\\HelpStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-borderdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-knobdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-depressed.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background-disabled.blp" );
				Preload( "UI\\Widgets\\Glues\\GlueScreen-PullDown-Arrow.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-gold.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-lumber.blp" );
				Preload( "war3mapMap.blp" );
				Preload( "UI\\Minimap\\minimap-gold.blp" );
				Preload( "UI\\Minimap\\minimap-neutralbuilding.blp" );
				Preload( "UI\\Minimap\\MinimapIconCircleOfPower.blp" );
				Preload( "UI\\Minimap\\minimap-hero.blp" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human05Interlude\\H05Medivh36.mp3" );
				Preload( "units\\creeps\\Medivh\\Medivh_portrait.mdx" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human05Interlude\\H05Arthas37.mp3" );
				Preload( "units\\human\\Arthas\\Arthas_portrait.mdx" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human05Interlude\\H05Medivh38.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human05Interlude\\H05Arthas39.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human05Interlude\\H05Medivh40.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human05Interlude\\H05Jaina41.mp3" );
				Preload( "units\\human\\Jaina\\Jaina_portrait.mdx" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human05Interlude\\H05Arthas42.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human05Interlude\\H05Jaina43.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human05Interlude\\H05Arthas44.mp3" );
				PreloadEnd( 5.00 );
			}

		} // class Human05Interlude_pld 

	}

