// Generated by .


	public partial class GameDefine 
	{

		public class Human02Interlude_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "Environment\\Sky\\DalaranSky\\DalaranSky.mdx" );
				Preload( "environment\\Sky\\DalaranSky\\DalaranSky.blp" );
				Preload( "Textures\\sun.blp" );
				Preload( "ReplaceableTextures\\Weather\\RaysOfLight.blp" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleSmall.blp" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleMed.blp" );
				Preload( "ReplaceableTextures\\CameraMasks\\White_mask.blp" );
				Preload( "Splats\\SplatData.slk" );
				Preload( "ReplaceableTextures\\Splats\\Splat01Mature.blp" );
				Preload( "UI\\TipStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-up.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-down.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-background-disabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-knob.blp" );
				Preload( "UI\\HelpStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-borderdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-knobdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-depressed.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background-disabled.blp" );
				Preload( "UI\\Widgets\\Glues\\GlueScreen-PullDown-Arrow.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-gold.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-lumber.blp" );
				Preload( "war3mapMap.blp" );
				Preload( "UI\\Minimap\\minimap-gold.blp" );
				Preload( "UI\\Minimap\\minimap-neutralbuilding.blp" );
				Preload( "UI\\Minimap\\MinimapIconCircleOfPower.blp" );
				Preload( "UI\\Minimap\\minimap-hero.blp" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Medivh28.mp3" );
				Preload( "units\\creeps\\Medivh\\Medivh_portrait.mdx" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Antonidas29.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Medivh30.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Antonidas31.mp3" );
				Preload( "Abilities\\Spells\\Undead\\Restore\\CityscapeCrystalLampLoop1.wav" );
				Preload( "Sound\\Ambient\\DoodadEffects\\CityscapeFountainLoop1.wav" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Jaina32.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Antonidas33.mp3" );
				Preload( "Abilities\\Spells\\Human\\MassTeleport\\MassTeleportTarget.mdx" );
				Preload( "Textures\\GenericGlowX.blp" );
				Preload( "Textures\\GenericGlow2c.blp" );
				Preload( "abilities\\Spells\\Human\\MassTeleport\\Rune1.blp" );
				Preload( "Abilities\\Spells\\Undead\\Unsummon\\CityscapeCrystalShield1.wav" );
				Preload( "Sound\\Ambient\\DoodadEffects\\CityScapeMagicRunesLoop1.wav" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Jaina34.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Antonidas35.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Jaina36.mp3" );
				Preload( "Sound\\Dialogue\\HumanCampaign\\Human02Interlude\\H02Antonidas37.mp3" );
				Preload( "Abilities\\Weapons\\SorceressMissile\\SorceressMissile.mdx" );
				Preload( "Textures\\Sentinel.blp" );
				Preload( "Textures\\Star8.blp" );
				Preload( "Textures\\Dust3.blp" );
				Preload( "Abilities\\Spells\\Human\\Slow\\SlowCaster.mdx" );
				Preload( "Textures\\Yellow_Glow_Dim2.blp" );
				Preload( "Abilities\\Spells\\Human\\slow\\slowtarget.mdx" );
				Preload( "abilities\\Spells\\Human\\Slow\\Tail_Dust3.blp" );
				Preload( "Abilities\\Spells\\Human\\Polymorph\\PolyMorphTarget.mdx" );
				Preload( "Textures\\Clouds8x8Fade.blp" );
				Preload( "Textures\\star5tga.blp" );
				Preload( "units\\critters\\Sheep\\Sheep.mdx" );
				Preload( "Textures\\SheepA.blp" );
				PreloadEnd( 5.00 );
			}

		} // class Human02Interlude_pld 

	}

