// Generated by .


	public partial class GameDefine 
	{

		public class n01_harvest_ai
		{
		//============================================================================
		//  Night Elf 01 -- lumber harvesting only -- AI Script
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				campaign_wood_peons = 6;
				SleepForever();
			}

		} // class n01_harvest_ai 

	}

