// Generated by .

	public partial class GameDefine 
	{

		public class n01_light_blue_ai
		{
		//============================================================================
		//  Night Elf 01 -- light blue player -- AI Script
		//============================================================================
			public BJPlayer user = Player(1);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				// all idle peons get put on lumber
				campaign_wood_peons = 99;
				SetBuildUnit( 4, PEASANT );
				SetBuildUnit( 4, PEON );
				CampaignDefender( EASY, 1, HIGH_FOOTMAN );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 2, FOOTMEN );
				SuicideOnPlayer(0,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 1, GRUNT );
				CampaignAttacker( EASY, 1, HEAD_HUNTER );
				SuicideOnPlayer(M3,user);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 2, FOOTMEN );
				CampaignAttacker( EASY, 1, RIFLEMAN );
				SuicideOnPlayer(M6,user);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 1, GRUNT );
				CampaignAttacker( EASY, 2, HEAD_HUNTER );
				SuicideOnPlayer(M3,user);
				while( true )
				{
					//*** WAVE 5+ ***
					InitAssaultGroup();
					CampaignAttacker( EASY, 3, FOOTMEN );
					CampaignAttacker( EASY, 2, RIFLEMAN );
					SuicideOnPlayer(M6,user);
					//*** WAVE 6+ ***
					InitAssaultGroup();
					CampaignAttacker( EASY, 2, GRUNT );
					CampaignAttacker( EASY, 1, HEAD_HUNTER );
					SuicideOnPlayer(M3,user);
				}
			}

		} // class n01_light_blue_ai 

	}

