// Generated by .


	public partial class GameDefine 
	{

		public class n01_pink_ai
		{
		//============================================================================
		//  Night Elf 01 -- pink player -- AI Script
		//============================================================================
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(BURROW,null);
				campaign_wood_peons = 100;
				campaign_gold_peons = 0;
				SleepForever();
			}

		} // class n01_pink_ai 

	}

