// Generated by .


	public partial class GameDefine 
	{

		public class n01_purple_ai
		{
		//============================================================================
		//  Night Elf 1 -- purple player -- AI Script
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SuicideUnits( FOOTMAN, 0, 0, 0, 0, 0, 0, 0, 0, 0 );
			}

		} // class n01_purple_ai 

	}

