// Generated by .


	public partial class GameDefine 
	{

		public class n02_pink_ai
		{
		//============================================================================
		//  Night Elf 02 -- pink player -- AI Script
		//============================================================================
			public BJPlayer  attacked = Player(4);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetReplacements(0,0,0);
				SetCaptainHome(DEFENSE_CAPTAIN,2013,568);
				SetCaptainHome(ATTACK_CAPTAIN,2010,570);
				CampaignDefenderEx( 0,0,1, GHOUL );
				WaitForSignal();
				//*** WAVE 1,2,3.... ***
				CampaignAttacker( EASY, 4, GARGOYLE );
				SuicideOnPlayer(M3,attacked);
				ForeverSuicideOnPlayer(M2,attacked);
			}

		} // class n02_pink_ai 

	}

