// Generated by .

	public partial class GameDefine 
	{

		public class n02_yellow_ai
		{
		//============================================================================
		//  Night Elf 02 -- yellow player -- AI Script
		//============================================================================
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(MOON_WELL,null);
				SetCaptainHome(DEFENSE_CAPTAIN,2534,-2171);
				CampaignDefender( EASY, 3, ARCHER );
				SleepForever();
			}

		} // class n02_yellow_ai 

	}

