// Generated by .


	public partial class GameDefine 
	{

		public class n04_green_ai
		{
		//============================================================================
		//  Night Elf 04 -- green player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(1);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(CORRUPT_WELL,null);
				SetReplacements(1,1,3);
				CampaignDefenderEx( 1,1,1, SKEL_WARRIOR );
				CampaignDefenderEx( 0,0,1, SHADOWDANCER );
				CampaignDefenderEx( 1,1,1, TRICKSTER );
				CampaignDefenderEx( 0,0,1, SOULSTEALER );
				CampaignDefenderEx( 1,1,1, SATYR );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, SATYR );
				CampaignAttackerEx( 1,1,2, TRICKSTER );
				SuicideOnPlayerEx(M2,M2,M1,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 8,8,10, SKEL_WARRIOR );
				SuicideOnPlayerEx(M5,M5,M4,user);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, SATYR );
				CampaignAttackerEx( 1,1,2, SHADOWDANCER );
				SuicideOnPlayerEx(M5,M5,M4,user);
				while( true )
				{
					//*** WAVE 4+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,6, SATYR );
					CampaignAttackerEx( 1,1,2, TRICKSTER );
					SuicideOnPlayerEx(M5,M5,M4,user);
					//*** WAVE 5+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, SKEL_WARRIOR );
					CampaignAttackerEx( 1,1,2, SHADOWDANCER );
					SuicideOnPlayerEx(M5,M5,M4,user);
					//*** WAVE 6+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, SATYR );
					CampaignAttackerEx( 1,1,2, SOULSTEALER );
					SuicideOnPlayerEx(M5,M5,M4,user);
				}
			}

		} // class n04_green_ai 

	}

