// Generated by .


	public partial class GameDefine 
	{

		public class n04_pink_ai
		{
		//============================================================================
		//  Night Elf 04 -- pink player -- AI Script
		//============================================================================
			public BJPlayer  User = Player(1);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				do_campaign_farms = false;
				CampaignDefender( EASY, 3, GARGOYLE );
				WaitForSignal();
				allow_signal_abort = true;
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,3, GARGOYLE );
				SuicideOnPlayerEx(M3,M3,M2,User);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, GARGOYLE );
				SuicideOnPlayerEx(M5,M5,M4,User);
				while( true )
				{
					//*** WAVE 3 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, GARGOYLE );
					SuicideOnPlayerEx(M5,M5,M4,User);
					//*** WAVE 4 ***
					InitAssaultGroup();
					CampaignAttackerEx( 4,4,5, GARGOYLE );
					SuicideOnPlayerEx(M5,M5,M4,User);
					//*** WAVE 5 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,3, GARGOYLE );
					SuicideOnPlayerEx(M5,M5,M4,User);
					if(  CommandsWaiting() !=0 )
						break;
				}
				SleepForever();
			}

		} // class n04_pink_ai 

	}

