// Generated by .


	public partial class GameDefine 
	{

		public class n04_red_ai
		{
		//============================================================================
		//  Night Elf 04 -- red player -- AI Script
		//============================================================================
			public BJPlayer undead = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(BURROW,null);
				do_campaign_farms = false;
				SetStagePoint(-4350,-103);
				SetBuildUnit( 4, PEON );
				SetBuildUnit( 2, ZEPPLIN );
				CampaignDefender( EASY, 1, GRUNT );
				CampaignDefender( EASY, 3, WYVERN );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 2, WYVERN );
				SuicideOnPlayer(0,undead);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 6, WYVERN );
				SuicideOnPlayer(M2,undead);
				while( true )
				{
					//*** WAVE 3 ***
					InitAssaultGroup();
					CampaignAttacker( EASY, 4, WYVERN );
					SuicideOnPlayer(M2,undead);
					//*** WAVE 4 ***
					InitAssaultGroup();
					CampaignAttacker( EASY, 8, WYVERN );
					SuicideOnPlayer(M2,undead);
					//*** WAVE 5 ***
					InitAssaultGroup();
					CampaignAttacker( EASY, 6, WYVERN );
					SuicideOnPlayer(M2,undead);
				}
			}

		} // class n04_red_ai 

	}

