// Generated by .


	public partial class GameDefine 
	{

		public class n04_brown_ai
		{
		//============================================================================
		//  Night Elf 4 -- brown player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(1);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SetReplacements(2,2,4);
				do_campaign_farms = false;
				campaign_wood_peons = 6;
				campaign_gold_peons = 0;
				SetBuildUnit( 6, PEASANT );
				CampaignDefenderEx( 1,1,1, FOOTMEN );
				CampaignDefenderEx( 1,1,1, PRIEST );
				CampaignDefenderEx( 0,0,1, RIFLEMAN);
				CampaignDefenderEx( 0,0,1, PALADIN );
				WaitForSignal();
				allow_signal_abort = true;
				// *** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, FOOTMAN );
				CampaignAttackerEx( 1,1,1, PALADIN );
				SuicideOnPlayer(M1,user);
				SetBuildUpgrEx( 0,0,1, UPG_MELEE );
				SetBuildUpgrEx( 0,0,1, UPG_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_MASONRY );
				// *** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 5,5,7, FOOTMAN );
				CampaignAttackerEx( 1,1,2, PRIEST );
				SuicideOnPlayerEx(M6,M6,M5,user);
				SetBuildUpgrEx( 1,1,1, UPG_DEFEND );
				SetBuildUpgrEx( 0,0,1, UPG_PRAYING );
				while( true )
				{
					// *** WAVE 3 ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,3, FOOTMAN );
					CampaignAttackerEx( 2,2,3, RIFLEMAN);
					CampaignAttackerEx( 1,1,1, PALADIN );
					SuicideOnPlayerEx(M6,M6,M5,user);
					// *** WAVE 4 ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,3, FOOTMAN );
					CampaignAttackerEx( 1,1,2, PRIEST );
					CampaignAttackerEx( 2,2,2, RIFLEMAN);
					CampaignAttackerEx( 0,0,1, PALADIN );
					SuicideOnPlayerEx(M6,M6,M5,user);
					if(  CommandsWaiting() !=0 )
						break;
				}
				SleepForever();
			}

		} // class n04_brown_ai 

	}

