// Generated by .


	public partial class GameDefine 
	{

		public class n05x03_ai
		{
		//============================================================================
		//  $Id: n05x03.ai,v 1.9 2003/04/26 11:30:56 bfitch Exp $
		//============================================================================
			public BJPlayer  user = PlayerEx(2);
			public void main(  )
			{
				// Original JassCode
				CampaignAI(NAGA_CORAL,null);
				SetAmphibious();
				SetBuildUnitEx( 1, 1, 1, NAGA_SLAVE );
				SetBuildUpgrEx( 1,1,2, UPG_SIREN );
				SetBuildUpgrEx( 0,0,1, UPG_NAGA_ENSNARE );
				SetBuildUpgrEx( 0,0,1, UPG_NAGA_ATTACK );
				SetBuildUpgrEx( 0,0,1, UPG_NAGA_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_NAGA_ABOLISH );
				CampaignDefenderEx( 1, 1, 2, NAGA_MYRMIDON );
				CampaignDefenderEx( 1, 1, 2, NAGA_SIREN );
				CampaignDefenderEx( 1, 1, 2, NAGA_REAVER );
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4, 4, 6, NAGA_REAVER );
				CampaignAttackerEx( 1, 1, 2, NAGA_MYRMIDON );
				SuicideOnPlayerEx(30,30,30,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4, 4, 6, NAGA_REAVER );
				CampaignAttackerEx( 1, 1, 2, NAGA_MYRMIDON );
				SuicideOnPlayerEx(M4,M4,M3,user);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4, 4, 6, NAGA_REAVER );
				CampaignAttackerEx( 2, 2, 4, NAGA_DRAGON );
				SuicideOnPlayerEx(M4,M4,M3,user);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 1, 1, 4, NAGA_MYRMIDON );
				CampaignAttackerEx( 2, 2, 3, NAGA_DRAGON );
				SuicideOnPlayerEx(M4,M4,M3,user);
			}

		} // class n05x03_ai 

	}

