// Generated by .


	public partial class GameDefine 
	{

		public class n06_tich_ai
		{
		//============================================================================
		//  Night Elf 06 -- Tichondrius -- AI Script
		//============================================================================
			public double TICH_CAPT_X = 6987;
			public double TICH_CAPT_Y = 2537;
			public double WAVE_CAPT_X = 5530;
			public double WAVE_CAPT_Y = 1270;
			public BJPlayer  user = Player(1);
			public int WAVE_DOOMS = UnitId( "nC00" );
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SetReplacementCount(99);
				SetCaptainHome( DEFENSE_CAPTAIN, TICH_CAPT_X, TICH_CAPT_Y );
				SetCaptainHome( ATTACK_CAPTAIN, WAVE_CAPT_X, WAVE_CAPT_Y );
				CampaignDefender( EASY, 1, TICHONDRIUS );
				CampaignDefender( EASY, 2, DOOMGUARD );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, FELLHOUND );
				CampaignAttackerEx( 1,1,2, WAVE_DOOMS );
				SuicideOnPlayerEx(M2,M2,M1,user);
				while( true )
				{
					//*** WAVE 2 ***
					InitAssaultGroup();
					CampaignAttackerEx( 1,1,4, INFERNAL );
					CampaignAttackerEx( 1,1,2, WAVE_DOOMS );
					SuicideOnPlayerEx(M5,M5,M4,user);
					//*** WAVE 3 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, FELLHOUND );
					CampaignAttackerEx( 1,1,2, INFERNAL );
					CampaignAttackerEx( 0,0,1, WAVE_DOOMS );
					SuicideOnPlayerEx(M6,M6,M5,user);
					//*** WAVE 4 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,6, FELLHOUND );
					CampaignAttackerEx( 2,2,3, WAVE_DOOMS );
					SuicideOnPlayerEx(M5,M5,M4,user);
				}
			}

		} // class n06_tich_ai 

	}

