// Generated by .


	public partial class GameDefine 
	{

		public class n07x07_ai
		{
		//==================================================================================================
		//  $Id: n07x07.ai,v 1.6 2003/04/19 15:22:18 rpardo Exp $
		//==================================================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetReplacements(1,1,3);
				CampaignDefenderEx( 0,0,1, NECRO );
				CampaignDefenderEx( 0,0,1, BANSHEE );
				SleepForever();
			}

		} // class n07x07_ai 

	}

