// Generated by .


	public partial class GameDefine 
	{

		public class n08_Light_Blue_ai
		{
		//============================================================================
		//  Night Elf 08 -- Blue player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(8);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SetBuildUnit( 1, TOWN_HALL );
				SetBuildUnit( 2, PEASANT );
				SetBuildUnit( 2, BARRACKS );
				SetBuildUnit( 1, HUMAN_ALTAR );
				SetBuildUnit( 1, LUMBER_MILL );
				SetBuildUnit( 1, BLACKSMITH );
				SetBuildUnit( 7, PEASANT );
				SetBuildUnit( 10, HOUSE );
				SetBuildUnit( 1, WORKSHOP );
				SetBuildUnit( 1, KEEP );
				SetBuildUnit( 3, GUARD_TOWER );
				SetBuildUnit( 1, SANCTUM );
				SetBuildUnit( 5, HOUSE );
				SetBuildUnit( 1, CASTLE );
				CampaignDefender (EASY, 4, FOOTMAN );
				CampaignDefender (EASY, 1, KNIGHT );
				CampaignDefender (EASY, 2, RIFLEMAN );
				CampaignDefender (EASY, 1, COPTER );
				CampaignDefender (EASY, 1, JAINA );
			}

		} // class n08_Light_Blue_ai 

	}

