// Generated by .


	public partial class GameDefine 
	{

		public class n08_yellow_ai
		{
		//============================================================================
		//  Night Elf 08 -- yellow player -- AI Script
		//============================================================================
			//integer wave_delay = 2*60
			public BJPlayer  user = Player(0);
			public void set_cheats(  )
			{
				// Original JassCode
				Cheat("warnings");
				Cheat("viewres");
				Cheat("av");
				Cheat("dg");
			}

		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				set_cheats();
				CampaignAI(ZIGGURAT_1,null);
				SetBuildUnit( 1, ACOLYTE );
				SetBuildUnit( 1, UNDEAD_MINE );
				SetBuildUnit( 1, NECROPOLIS_1 );
				SetBuildUnit( 6, ACOLYTE );
				SetBuildUnit( 1, CRYPT );
				SetBuildUnit( 1, GRAVEYARD );
				SetBuildUnit( 3, ZIGGURAT_1 );
				SetBuildUnit( 3, ZIGGURAT_2 );
				SetBuildUnit( 1, UNDEAD_ALTAR );
				SetBuildUnit( 1, SAC_PIT );
				SetBuildUnit( 2, CRYPT );
				SetBuildUnit( 1, DAMNED_TEMPLE );
				SetBuildUnit( 1, SLAUGHTERHOUSE );
				SetBuildUnit( 7, ZIGGURAT_1 );
				SetBuildUnit( 7, ZIGGURAT_2 );
				SetBuildUnit( 1, NECROPOLIS_2 );
				SetBuildUnit( 1, NECROPOLIS_3 );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 6, GHOUL );
				SuicideOnPlayer(0,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 6, GHOUL );
				CampaignAttacker( EASY, 1, NECRO );
				SuicideOnPlayer(3*60,user);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 8, GHOUL );
				CampaignAttacker( EASY, 2, NECRO );
				SuicideOnPlayer(3*60,user);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 8, GHOUL );
				CampaignAttacker( EASY, 2, NECRO );
				CampaignAttacker( EASY, 1, MEAT_WAGON );
				SuicideOnPlayer(3*60,user);
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 8, GHOUL );
				CampaignAttacker( EASY, 2, NECRO );
				CampaignAttacker( EASY, 2, MEAT_WAGON );
				SuicideOnPlayer(2*60,user);
				// repeat previous wave over and over until mission ends
				ForeverSuicideOnPlayer(2*60,user);
			}

		} // class n08_yellow_ai 

	}

