// Generated by .


	public partial class GameDefine 
	{

		public class n08x05_ai
		{
		//============================================================================
		//  $Id: n08x05.ai,v 1.17.2.1 2003/05/09 09:17:04 abond Exp $
		//============================================================================
			public BJPlayer  user = PlayerEx(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetReplacements(1,1,3);
				DoCampaignFarms(false);
				SetBuildUpgrEx( 1, 1, 1, UPG_BLK_SPHINX );
				CampaignDefenderEx( 1, 1, 2, ABOMINATION );
				CampaignDefenderEx( 1, 1, 2, NECRO );
				CampaignDefenderEx( 0, 0, 1, FROST_WYRM );
				CampaignDefenderEx( 1, 1, 1, GARGOYLE );
				CampaignDefenderEx( 0, 0, 1, DREAD_LORD );
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,3, GARGOYLE );
				CampaignAttackerEx( 3,3,3, GHOUL );
				CampaignAttackerEx( 3,3,3, CRYPT_FIEND );
				SuicideOnPlayerEx(M1,M1,M1,user);
				SetBuildUpgrEx( 0,0,1, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 0,0,1, UPG_CR_ATTACK );
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 5,5,5, GHOUL );
				SuicideOnPlayerEx(M2,M2,M2,user);
				SetBuildUpgrEx( 0,0,1, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 0,0,1, UPG_CR_ARMOR );
				SetBuildUpgrEx( 1,1,2, UPG_NECROS );
				SetBuildUpgrEx( 1,1,2, UPG_BANSHEE );
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,3, GARGOYLE );
				CampaignAttackerEx( 4,4,4, NECRO );
				SuicideOnPlayerEx(M2,M2,M2,user);
				SetBuildUpgrEx( 0,0,1, UPG_PLAGUE );
				SetBuildUpgrEx( 1,1,2, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 1,1,2, UPG_CR_ATTACK );
				SetBuildUpgrEx( 0,0,1, UPG_SKEL_MASTERY );
				SetBuildUpgrEx( 0,0,1, UPG_WYRM_BREATH );
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,4, NECRO );
				CampaignAttackerEx( 2,2,2, GHOUL );
				CampaignAttackerEx( 2,2,2, GARGOYLE );
				SuicideOnPlayerEx(M2,M2,M2,user);
				SetBuildUpgrEx( 1,1,2, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 1,1,2, UPG_CR_ARMOR );
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,3, GARGOYLE );
				CampaignAttackerEx( 2,2,2, ABOMINATION );
				SuicideOnPlayerEx(M2,M2,M2,user);
				SetBuildUpgrEx( 2,2,3, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 2,2,3, UPG_CR_ATTACK );
				SetBuildUpgrEx( 1,1,1, UPG_GHOUL_FRENZY);
				SetBuildUpgrEx( 1,1,1, UPG_SKEL_MASTERY);
				SetBuildUpgrEx( 1,1,1, UPG_WYRM_BREATH );
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttackerEx( 1,1,1, ABOMINATION );
				CampaignAttackerEx( 3,3,3, NECRO );
				CampaignAttackerEx( 2,2,2, GHOUL );
				CampaignAttackerEx( 2,2,2, GARGOYLE );
				SuicideOnPlayerEx(M2,M2,M2,user);
				SetBuildUpgrEx( 2,2,3, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 2,2,3, UPG_CR_ARMOR );
				SetBuildUpgrEx( 1,1,1, UPG_PLAGUE );
				SetBuildUpgrEx( 2,2,2, UPG_NECROS );
				SetBuildUpgrEx( 2,2,2, UPG_BANSHEE );
				while( true )
				{
					//*** WAVE 7+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 1,1,1, FROST_WYRM );
					CampaignAttackerEx( 3,3,3, GARGOYLE );
					SuicideOnPlayerEx(M2,M2,M2,user);
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,2, BANSHEE );
					CampaignAttackerEx( 8,8,8, GHOUL );
					SuicideOnPlayerEx(M2,M2,M2,user);
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,3, GARGOYLE );
					CampaignAttackerEx( 1,1,1, ABOMINATION );
					CampaignAttackerEx( 3,3,3, NECRO );
					SuicideOnPlayerEx(M2,M2,M2,user);
					InitAssaultGroup();
					CampaignAttackerEx( 1,1,1, ABOMINATION );
					CampaignAttackerEx( 4,4,4, NECRO );
					CampaignAttackerEx( 2,2,2, GHOUL );
					SuicideOnPlayerEx(M2,M2,M2,user);
				}
			}

		} // class n08x05_ai 

	}

