// Generated by .


	public partial class GameDefine 
	{

		public class n08x11_ai
		{
		//============================================================================
		//  $Id: n08x11.ai,v 1.8.2.1 2003/05/09 09:17:04 abond Exp $
		//============================================================================
			public BJPlayer  user = PlayerEx(2);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetReplacements(1,1,3);
				DoCampaignFarms(false);
				CampaignDefenderEx( 1, 1, 2, NECRO );
				CampaignDefenderEx( 1, 1, 2, BANSHEE );
				SleepForever();
			}

		} // class n08x11_ai 

	}

