// Generated by .


	public partial class GameDefine 
	{

		public class n08x03_ai
		{
		//============================================================================
		//  Night Elf 8 Ex -- players 3 -- AI Script
		//============================================================================
			public int SWISP = UnitId( "e001" );
			public int SHUNTRESS = UnitId( "e000" );
			public int SARCHER = UnitId( "e005" );
			public int SANCIENTWAR = UnitId( "e009" );
			public int SPROTECTOR = UnitId( "e008" );
			public int SMOONWELL = UnitId( "e007" );
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(MOON_WELL,null);
				SetReplacements(9,9,9);
				DoCampaignFarms(false);
				SetPeonsRepair(true);
				SetBuildUnitEx( 2,2,2, SWISP );
				SetBuildUnitEx( 2,2,2, SPROTECTOR );
				SetBuildUnitEx( 1,1,1, SANCIENTWAR );
				SetBuildUnitEx( 2,2,2, SMOONWELL );
				CampaignDefenderEx( 1, 1, 1, SARCHER );
				CampaignDefenderEx( 1, 1, 1, SHUNTRESS );
				SleepForever();
			}

		} // class n08x03_ai 

	}

