// Generated by .


	public partial class GameDefine 
	{

		public class NightElf07_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "ReplaceableTextures\\CameraMasks\\White_mask.blp" );
				Preload( "Splats\\SplatData.slk" );
				Preload( "ReplaceableTextures\\Splats\\Splat01Mature.blp" );
				Preload( "units\\nightelf\\HeroMoonPriestess\\HeroMoonPriestess.mdx" );
				Preload( "units\\NightElf\\HeroMoonPriestess\\PriestessOfTheMoon.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNPriestessOfTheMoon.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNPriestessOfTheMoon.blp" );
				Preload( "UI\\Widgets\\Console\\Human\\CommandButton\\human-button-lvls-overlay.blp" );
				Preload( "units\\nightelf\\HeroMoonPriestess\\HeroMoonPriestess_portrait.mdx" );
				Preload( "Abilities\\Spells\\NightElf\\TrueshotAura\\TrueshotAura.mdx" );
				Preload( "abilities\\Spells\\NightElf\\TrueshotAura\\quartercircle2.blp" );
				Preload( "abilities\\Spells\\NightElf\\TrueshotAura\\tjcrosshair.blp" );
				Preload( "units\\nightelf\\Furion\\Furion.mdx" );
				Preload( "units\\NightElf\\Furion\\Furion.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNFurion.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNFurion.blp" );
				Preload( "units\\nightelf\\Furion\\Furion_portrait.mdx" );
				Preload( "Abilities\\Spells\\NightElf\\ThornsAura\\ThornsAura.mdx" );
				Preload( "abilities\\Spells\\NightElf\\ThornsAura\\Thorns.blp" );
				Preload( "Abilities\\Spells\\Human\\Brilliance\\Brilliance.mdx" );
				Preload( "abilities\\Spells\\Human\\Brilliance\\TjShockwave2.blp" );
				Preload( "Abilities\\Spells\\Items\\AIlb\\AIlbTarget.mdx" );
				Preload( "Abilities\\Spells\\Items\\AIfb\\AIfbTarget.mdx" );
				Preload( "Abilities\\Spells\\Items\\AIob\\AIobTarget.mdx" );
				Preload( "abilities\\Spells\\Items\\AIob\\Ice3b_Ice3b_A.blp" );
				Preload( "Textures\\snowflake.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor03.blp" );
				Preload( "ReplaceableTextures\\TeamGlow\\TeamGlow03.blp" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleMed.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor05.blp" );
				Preload( "ReplaceableTextures\\TeamGlow\\TeamGlow05.blp" );
				Preload( "Environment\\Sky\\FelwoodSky\\FelwoodSky.mdx" );
				Preload( "environment\\Sky\\FelwoodSky\\FelwoodSky.blp" );
				Preload( "Sound\\Ambient\\DoodadEffects\\LordaeronSummerHumanTorchLoop1.wav" );
				Preload( "UI\\TipStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\NightElf\\nightelf-options-button-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-up.blp" );
				Preload( "UI\\Widgets\\EscMenu\\NightElf\\nightelf-options-button-background-down.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-down.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-background-disabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\NightElf\\nightelf-options-button-background-disabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\NightElf\\nightelf-slider-knob.blp" );
				Preload( "UI\\HelpStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-borderdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-knobdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\NightElf\\nightelf-checkbox-depressed.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background-disabled.blp" );
				Preload( "UI\\Widgets\\Glues\\GlueScreen-PullDown-Arrow.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-gold.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-lumber.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor04.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor11.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor12.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor13.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor14.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-gold-disabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-lumber-disabled.blp" );
				Preload( "war3mapMap.blp" );
				Preload( "UI\\Minimap\\minimap-gold.blp" );
				Preload( "UI\\Minimap\\minimap-neutralbuilding.blp" );
				Preload( "UI\\Minimap\\MinimapIconCircleOfPower.blp" );
				Preload( "UI\\Minimap\\minimap-hero.blp" );
				Preload( "Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdx" );
				Preload( "Splats\\SpawnData.slk" );
				Preload( "Objects\\Spawnmodels\\Demon\\DemonBlood\\DemonBloodPitlord.mdx" );
				Preload( "Textures\\BloodWhiteSmall.blp" );
				Preload( "Objects\\Spawnmodels\\Undead\\UndeadDissipate\\UndeadDissipate.mdx" );
				Preload( "Textures\\Ghost1.blp" );
				Preload( "Textures\\Clouds8x8Fade.blp" );
				Preload( "Abilities\\Spells\\Human\\MassTeleport\\MassTeleportTo.mdx" );
				Preload( "Textures\\DemonRune2.blp" );
				Preload( "abilities\\Spells\\Human\\MassTeleport\\Rune1.blp" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf07\\N07Jaina02.mp3" );
				Preload( "units\\human\\Jaina\\Jaina_portrait.mdx" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf07\\N07Furion02.mp3" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf07\\N07Furion02a.mp3" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf07\\N07Tyrande03.mp3" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf07\\N07Furion04.mp3" );
				Preload( "Sound\\Ambient\\DoodadEffects\\LordaeronSummerBrazierLoop1.wav" );
				Preload( "Abilities\\Spells\\NightElf\\StarFall\\StarFallCaster.mdx" );
				Preload( "abilities\\Spells\\NightElf\\Starfall\\Moon_Cresent.blp" );
				Preload( "Textures\\DemonRune1.blp" );
				Preload( "Textures\\Shockwave11.blp" );
				Preload( "Abilities\\Spells\\NightElf\\ReviveNightElf\\ReviveNightElf.mdx" );
				Preload( "Textures\\firering4.blp" );
				Preload( "Textures\\GenericGlow2_64.blp" );
				Preload( "Environment\\BlightDoodad\\BlightDoodad.mdx" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf07\\N07Archimonde04.mp3" );
				Preload( "units\\demon\\Warlock\\Warlock_portrait.mdx" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf07\\N07Jaina06.mp3" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf07\\N07Tyrande07.mp3" );
				Preload( "buildings\\nightelf\\EntangledGoldMine\\EntangledGoldMine.mdx" );
				Preload( "buildings\\NightElf\\EntangledGoldmine\\LightRoots.blp" );
				Preload( "buildings\\NightElf\\EntangledGoldmine\\Lightbush.blp" );
				Preload( "SharedModels\\EntangleWisp.mdx" );
				Preload( "Abilities\\Spells\\NightElf\\EntangleMine\\Roots.mdx" );
				Preload( "abilities\\Spells\\NightElf\\EntangleMine\\Roots.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNAttack.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNAttack.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNStop.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNStop.blp" );
				Preload( "UI\\Widgets\\Console\\Human\\CommandButton\\human-activebutton.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNMove.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNMove.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNPatrol.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNPatrol.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNHoldPosition.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNHoldPosition.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNSkillz.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNSkillz.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNEntanglingRoots.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNEntanglingRoots.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNEnt.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNEnt.blp" );
				Preload( "ReplaceableTextures\\PassiveButtons\\PASBTNThorns.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISPASBTNThorns.blp" );
				Preload( "UI\\Widgets\\Console\\Human\\infocard-neutral-attack-melee.blp" );
				Preload( "UI\\Widgets\\Console\\Human\\infocard-armor-hero.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNThorns.blp" );
				Preload( "UI\\Widgets\\Console\\Human\\infocard-heroattributes-int.blp" );
				Preload( "ReplaceableTextures\\CommandButtons\\BTNHornOfCenarius.blp" );
				Preload( "ReplaceableTextures\\CommandButtonsDisabled\\DISBTNHornOfCenarius.blp" );
				Preload( "Abilities\\Spells\\NightElf\\TargetArtLumber\\TargetArtLumber.mdx" );
				Preload( "abilities\\Spells\\NightElf\\TargetArtLumber\\GenericGlow2.blp" );
				Preload( "Abilities\\Spells\\NightElf\\TargetArtLumber\\WispHarvestLumber1.wav" );
				Preload( "Units\\NightElf\\Owl\\Owl.mdx" );
				Preload( "Textures\\sentinelspell.blp" );
				Preload( "Textures\\Green_Glow3.blp" );
				PreloadEnd( 5.0 );
			}

		} // class NightElf07_pld 

	}

