// Generated by .


	public partial class GameDefine 
	{

		public class NightElf06Interlude_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "Environment\\Sky\\Sky\\SkyLight.mdx" );
				Preload( "environment\\Sky\\Sky\\Streaks.blp" );
				Preload( "Textures\\sun.blp" );
				Preload( "Textures\\megaWrap512.blp" );
				Preload( "Splats\\SplatData.slk" );
				Preload( "ReplaceableTextures\\Splats\\Splat01Mature.blp" );
				Preload( "ReplaceableTextures\\CameraMasks\\Black_mask.blp" );
				Preload( "UI\\TipStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\Orc\\orc-options-button-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-up.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Orc\\orc-options-button-background-down.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-down.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-background-disabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Orc\\orc-slider-knob.blp" );
				Preload( "UI\\HelpStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-borderdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-knobdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Orc\\orc-checkbox-depressed.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background-disabled.blp" );
				Preload( "UI\\Widgets\\Glues\\GlueScreen-PullDown-Arrow.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-gold.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-lumber.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor03.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor04.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor06.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor07.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor08.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor10.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor12.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor13.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor14.blp" );
				Preload( "war3mapMap.blp" );
				Preload( "UI\\Minimap\\minimap-gold.blp" );
				Preload( "UI\\Minimap\\minimap-neutralbuilding.blp" );
				Preload( "UI\\Minimap\\MinimapIconCircleOfPower.blp" );
				Preload( "UI\\Minimap\\minimap-hero.blp" );
				Preload( "Sound\\Ambient\\DoodadEffects\\WaterWaterFallLoop1.wav" );
				Preload( "Environment\\SmallBuildingFire\\SmallBuildingFire1.mdx" );
				Preload( "Textures\\Clouds8x8ModFire.blp" );
				Preload( "Environment\\LargeBuildingFire\\LargeBuildingFire2.mdx" );
				Preload( "Sound\\Ambient\\DoodadEffects\\LordaeronSummerHumanTorchLoop1.wav" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Tyrande29.mp3" );
				Preload( "units\\nightelf\\HeroMoonPriestess\\HeroMoonPriestess_portrait.mdx" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleSmall.blp" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleMed.blp" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Furion30.mp3" );
				Preload( "units\\nightelf\\Furion\\Furion_portrait.mdx" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Thrall31.mp3" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Furion32.mp3" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Thrall33.mp3" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Jaina34.mp3" );
				Preload( "units\\human\\Jaina\\Jaina_portrait.mdx" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Tyrande35.mp3" );
				Preload( "Abilities\\Spells\\NightElf\\Rejuvenation\\RejuvenationTarget.mdx" );
				Preload( "Textures\\GenericGlow2b.blp" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Medivh36.mp3" );
				Preload( "units\\creeps\\Medivh\\Medivh_portrait.mdx" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Furion37.mp3" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Medivh38.mp3" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Medivh39.mp3" );
				Preload( "Sound\\Ambient\\WindLoopStereo.wav" );
				Preload( "Abilities\\Spells\\Human\\ReviveHuman\\revivehuman.mdx" );
				Preload( "Textures\\firering4.blp" );
				Preload( "Textures\\GenericGlow2_64.blp" );
				Preload( "Textures\\Yellow_Star.blp" );
				Preload( "Units\\Orc\\Wolfrider\\WolfriderYes3.wav" );
				Preload( "Sound\\Buildings\\Fire\\OrcHumanMediumBuildingFire1.wav" );
				Preload( "Sound\\Buildings\\Fire\\OrcHumanSmallBuildingFire1.wav" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Medivh40.mp3" );
				Preload( "Units\\Critters\\OrcJuggernaught\\OrcJuggernaught.mdx" );
				Preload( "units\\Critters\\OrcJuggernaught\\Orc_juggernaught.blp" );
				Preload( "Abilities\\Weapons\\GuardTowerMissile\\GuardTowerMissile.mdx" );
				Preload( "Textures\\ArrowMissile.blp" );
				Preload( "Textures\\RibbonNE1_White.blp" );
				Preload( "Abilities\\Weapons\\Axe\\AxeMissile.mdx" );
				Preload( "abilities\\Weapons\\Axe\\TrollPink.blp" );
				Preload( "abilities\\weapons\\catapult\\catapultmissile.mdx" );
				Preload( "Textures\\rock64.blp" );
				Preload( "Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdx" );
				Preload( "abilities\\Weapons\\FireBallMissile\\Dust6Color.blp" );
				Preload( "Textures\\lensflare1A.blp" );
				Preload( "Textures\\Dust5ABlack.blp" );
				Preload( "abilities\\Weapons\\FireBallMissile\\Dust6ColorRed.blp" );
				Preload( "Abilities\\Weapons\\GyroCopter\\GyroCopterImpact.mdx" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Medivh41.mp3" );
				Preload( "ReplaceableTextures\\Weather\\snow.blp" );
				Preload( "Environment\\Sky\\LordaeronWinterSky\\LordaeronWinterSky.mdx" );
				Preload( "Textures\\LordaeronSkyWrap.blp" );
				Preload( "ReplaceableTextures\\Splats\\CraterUberSplat.blp" );
				Preload( "Abilities\\Weapons\\GryphonRiderMissile\\GryphonRiderMissile.mdx" );
				Preload( "abilities\\Weapons\\GryphonRiderMissile\\Griffon.blp" );
				Preload( "Textures\\E_Smoke_Anim256.blp" );
				Preload( "Textures\\star32.blp" );
				Preload( "Textures\\Blue_Star2.blp" );
				Preload( "Abilities\\Weapons\\GreenDragonMissile\\GreenDragonMissile.mdx" );
				Preload( "Textures\\Dust6.blp" );
				Preload( "Textures\\GenericGlow2c.blp" );
				Preload( "Textures\\Clouds8x8Fade.blp" );
				Preload( "Textures\\star2_32.blp" );
				Preload( "Splats\\SpawnData.slk" );
				Preload( "Objects\\Spawnmodels\\Human\\HumanBlood\\HumanBloodFootman.mdx" );
				Preload( "Textures\\BloodWhiteSmall.blp" );
				Preload( "Objects\\Spawnmodels\\Human\\HumanLargeDeathExplode\\HumanLargeDeathExplode.mdx" );
				Preload( "Sound\\Buildings\\Fire\\OrcHumanLargeBuildingFire1.wav" );
				Preload( "Environment\\SmallBuildingFire\\SmallBuildingFire2.mdx" );
				Preload( "Environment\\LargeBuildingFire\\LargeBuildingFire0.mdx" );
				Preload( "Environment\\LargeBuildingFire\\LargeBuildingFire1.mdx" );
				Preload( "Objects\\Spawnmodels\\Human\\HumanBlood\\HumanBloodKnight.mdx" );
				Preload( "Sound\\Dialogue\\NightElfCampaign\\NightElf06Interlude\\N06Medivh42.mp3" );
				PreloadEnd( 5.0 );
			}

		} // class NightElf06Interlude_pld 

	}

