// Generated by .


	public partial class GameDefine 
	{

		public class o03_forestgreen_ai
		{
		//============================================================================
		//  Orc 3 -- forest green player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(0);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SetReplacements(1,1,3);
				SetBuildUnit( 8, PEASANT );
				CampaignDefenderEx( 1,1,2, FOOTMEN );
				CampaignDefenderEx( 1,1,1, SORCERESS );
				WaitForSignal();
				// *** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 6,6,8, FOOTMAN );
				CampaignAttackerEx( 1,1,2, SORCERESS );
				SuicideOnPlayer(0,user);
				SetBuildUpgrEx( 0,0,1, UPG_MELEE );
				SetBuildUpgrEx( 0,0,1, UPG_ARMOR );
				SetBuildUpgrEx( 0,0,2, UPG_MASONRY );
				SetBuildUpgrEx( 1,1,1, UPG_DEFEND );
				SetBuildUpgrEx( 0,0,1, UPG_PRAYING );
				SetBuildUpgrEx( 0,0,1, UPG_SORCERY );
				// *** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 6,6,8, FOOTMAN );
				CampaignAttackerEx( 1,1,2, PRIEST );
				SuicideOnPlayerEx(M8,M8,M7,user);
				// *** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, FOOTMAN );
				CampaignAttackerEx( 2,2,3, SORCERESS );
				SuicideOnPlayerEx(M8,M8,M7,user);
				SetBuildUpgrEx( 1,1,2, UPG_MELEE );
				SetBuildUpgrEx( 1,1,2, UPG_ARMOR );
				SetBuildUpgrEx( 2,2,2, UPG_PRAYING );
				SetBuildUpgrEx( 2,2,2, UPG_SORCERY );
				while( true )
				{
					// *** WAVE 4 ***
					InitAssaultGroup();
					CampaignAttackerEx( 6,6,6, FOOTMAN );
					CampaignAttackerEx( 2,2,2, PRIEST );
					CampaignAttackerEx( 2,2,3, SORCERESS );
					SuicideOnPlayerEx(M8,M8,M7,user);
					// *** WAVE 5 ***
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,6, FOOTMAN );
					CampaignAttackerEx( 2,2,2, PRIEST );
					CampaignAttackerEx( 3,3,3, SORCERESS );
					SuicideOnPlayerEx(M8,M8,M7,user);
				}
			}

		} // class o03_forestgreen_ai 

	}

