// Generated by .


	public partial class GameDefine 
	{

		public class o04_lightblue_ai
		{
		//============================================================================
		//  Orc 04 -- light blue player -- AI Script
		//============================================================================
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(MOON_WELL,null);
				campaign_wood_peons = 100;
				SleepForever();
			}

		} // class o04_lightblue_ai 

	}

