// Generated by .


	public partial class GameDefine 
	{

		public class o04_teal_ai
		{
		//============================================================================
		//  Orc 04 -- Teal player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(MOON_WELL,null);
				campaign_wood_peons = 100;
				SetBuildUnit( 5, WISP );
				SetBuildUpgrEx( 1,1,1, UPG_HIPPO_TAME );
				CampaignDefenderEx( 1,1,2, ARCHER );
				CampaignDefenderEx( 1,1,1, DRYAD );
				CampaignDefenderEx( 1,1,2, HIPPO );
				CampaignDefenderEx( 1,1,2, HIPPO_RIDER );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,3, HIPPO_RIDER );
				SuicideOnPlayerEx(M1,M1,0,user);
				SetBuildUpgrEx( 0,0,1, UPG_STR_MOON );
				SetBuildUpgrEx( 0,0,1, UPG_STR_WILD );
				SetBuildUpgrEx( 1,1,1, UPG_ULTRAVISION );
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,5, HIPPO_RIDER );
				SuicideOnPlayerEx(M8,M8,M7,user);
				SetBuildUpgrEx( 0,0,1, UPG_MOON_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_HIDES );
				SetBuildUpgrEx( 0,0,1, UPG_GLAIVE );
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 1,1,2, BALLISTA );
				CampaignAttackerEx( 4,4,5, ARCHER );
				CampaignAttackerEx( 3,3,5, DRYAD );
				SuicideOnPlayerEx(M8,M8,M7,user);
				SetBuildUpgrEx( 1,1,1, UPG_BOWS );
				SetBuildUpgrEx( 1,1,2, UPG_STR_MOON );
				SetBuildUpgrEx( 1,1,2, UPG_STR_WILD );
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 6,6,9, HIPPO_RIDER );
				SuicideOnPlayerEx(M8,M8,M7,user);
				SetBuildUpgrEx( 0,0,1, UPG_MARKSMAN );
				SetBuildUpgrEx( 1,1,2, UPG_MOON_ARMOR );
				SetBuildUpgrEx( 1,1,2, UPG_HIDES );
				SetBuildUpgrEx( 1,1,1, UPG_GLAIVE );
				SetBuildUpgrEx( 0,0,1, UPG_BOLT );
				while( true )
				{
					//*** WAVE 5 ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,3, BALLISTA );
					CampaignAttackerEx( 5,5,6, ARCHER );
					CampaignAttackerEx( 4,4,6, DRYAD );
					SuicideOnPlayerEx(M8,M8,M7,user);
					//*** WAVE 6 ***
					InitAssaultGroup();
					CampaignAttackerEx( 7,7,10, HIPPO_RIDER );
					SuicideOnPlayerEx(M8,M8,M7,user);
				}
			}

		} // class o04_teal_ai 

	}

