// Generated by .


	public partial class GameDefine 
	{

		public class o05_lightblue_ai
		{
		//============================================================================
		//  Orc 05 -- light blue player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(MOON_WELL,null);
				SetReplacements(2,2,4);
				// don't harvest immediately
				campaign_wood_peons = 0;
				SetBuildUnit( 1, WISP );
				SetBuildUnit( 1, ELF_ALTAR );
				SetBuildUnit( 1, HUNTERS_HALL );
				SetBuildUnit( 8, WISP );
				SetBuildUnitEx( 3,3,3, ANCIENT_PROTECT );
				CampaignDefender( EASY, 3, ARCHER );
				CampaignDefender( EASY, 2, HUNTRESS );
				SetBuildUpgrEx( 0,0,1, UPG_BLESSING );
				// wait to start harvesting
				WaitForSignal();
				campaign_wood_peons = 0;
				// wait to start attack waves
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,5, ARCHER );
				CampaignAttackerEx( 1,1,1, ANCIENT_PROTECT );
				SuicideOnPlayerEx(M6,M6,M6,user);
				SetBuildUpgrEx( 0,0,1, UPG_STR_MOON );
				SetBuildUpgrEx( 1,1,1, UPG_ULTRAVISION );
				//*** WAVE 2 ***                                
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, ARCHER );
				CampaignAttackerEx( 2,2,3, ANCIENT_PROTECT );
				SuicideOnPlayerEx(M8,M8,M7,user);
				SetBuildUpgrEx( 0,0,1, UPG_MOON_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_GLAIVE );
				//*** WAVE 3 ***                                
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,3, ARCHER );
				CampaignAttackerEx( 2,2,4, HUNTRESS );
				CampaignAttackerEx( 1,1,1, BALLISTA );
				CampaignAttackerEx( 1,1,1, ANCIENT_PROTECT );
				SuicideOnPlayerEx(M8,M8,M7,user);
				SetBuildUpgrEx( 1,1,1, UPG_BOWS );
				SetBuildUpgrEx( 1,1,2, UPG_STR_MOON );
				//*** WAVE 4 ***                                
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,5, ARCHER );
				CampaignAttackerEx( 2,2,3, HUNTRESS );
				CampaignAttackerEx( 2,2,3, ANCIENT_PROTECT );
				SuicideOnPlayerEx(M8,M8,M7,user);
				SetBuildUpgrEx( 1,1,1, UPG_MARKSMAN );
				SetBuildUpgrEx( 1,1,2, UPG_MOON_ARMOR );
				//*** WAVE 5 ***                                
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, HUNTRESS );
				CampaignAttackerEx( 1,1,2, BALLISTA );
				CampaignAttackerEx( 1,1,2, ANCIENT_PROTECT );
				SuicideOnPlayerEx(M8,M8,M7,user);
				SetBuildUpgrEx( 1,1,1, UPG_GLAIVE );
				SetBuildUpgrEx( 1,1,1, UPG_BOLT );
				SetBuildUpgrEx( 2,2,2, UPG_MOON_ARMOR );
				SetBuildUpgrEx( 2,2,2, UPG_STR_MOON );
				while( true )
				{
					//*** WAVE 6 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,5, ARCHER );
					CampaignAttackerEx( 3,3,4, ANCIENT_PROTECT );
					SuicideOnPlayerEx(M8,M8,M7,user);
					//*** WAVE 7 ***
					InitAssaultGroup();
					CampaignAttackerEx( 1,1,2, ARCHER );
					CampaignAttackerEx( 2,2,3, HUNTRESS );
					CampaignAttackerEx( 2,2,3, BALLISTA );
					CampaignAttackerEx( 1,1,2, ANCIENT_PROTECT );
					SuicideOnPlayerEx(M8,M8,M7,user);
					//*** WAVE 8 ***
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,8, HUNTRESS );
					CampaignAttackerEx( 1,1,2, BALLISTA );
					CampaignAttackerEx( 2,2,3, ANCIENT_PROTECT );
					SuicideOnPlayerEx(M8,M8,M7,user);
				}
			}

		} // class o05_lightblue_ai 

	}

