// Generated by .


	public partial class GameDefine 
	{

		public class o05_yellow_ai
		{
		//============================================================================
		//  Orc 05 -- yellow player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
			public int  factor = 1;
			public void MikesSuicide( int easy , int med , int hard , BJPlayer user )
			{
				// Original JassCode
				if(  CommandsWaiting()>0  )
				{
					factor = 2;
					PopLastCommand();
				}
				SuicideOnPlayerEx(easy/factor, med/factor, hard/factor, user);
			}

		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(MOON_WELL,null);
				campaign_wood_peons = 100;
				SetBuildUnit( 1, TREE_LIFE );
				SetBuildUnit( 1, WISP );
				SetBuildUnit( 1, ANCIENT_WAR );
				SetBuildUnit( 2, WISP );
				SetBuildUnit( 1, ELF_ALTAR );
				SetBuildUnit( 1, HUNTERS_HALL );
				SetBuildUnit( 1, TREE_AGES );
				SetBuildUnit( 1, ANCIENT_WIND );
				SetBuildUnit( 1, ANCIENT_LORE );
				SetBuildUnit( 1, TREE_ETERNITY );
				SetBuildUnit( 8, WISP );
				CampaignDefender( EASY, 3, ARCHER );
				CampaignDefender( EASY, 2, HUNTRESS );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 2, ARCHER );
				SuicideOnPlayer(0,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 2, ARCHER );
				CampaignAttacker( EASY, 1, HUNTRESS );
				SuicideOnPlayer(3*60,user);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 2, ARCHER );
				CampaignAttacker( EASY, 2, HUNTRESS );
				CampaignAttacker( EASY, 1, BALLISTA );
				MikesSuicide(4*60,4*60,4*60,user);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 5, ARCHER );
				CampaignAttacker( EASY, 2, HUNTRESS );
				MikesSuicide(6*60,6*60,6*60,user);
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 3, ARCHER );
				CampaignAttacker( EASY, 1, HUNTRESS );
				MikesSuicide(2*60,2*60,2*60,user);
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 4, HUNTRESS );
				CampaignAttacker( EASY, 2, BALLISTA );
				CampaignAttacker( EASY, 1, WISP );
				MikesSuicide(6*60,6*60,6*60,user);
				//*** WAVE 7 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 2, HUNTRESS );
				CampaignAttacker( EASY, 1, ANCIENT_PROTECT );
				MikesSuicide(3*60,3*60,3*60,user);
				//*** WAVE 8 ***
				InitAssaultGroup();
				CampaignAttacker( EASY, 6, ARCHER );
				MikesSuicide(4*60,4*60,4*60,user);
				while( true )
				{
					//*** WAVE 9 ***
					InitAssaultGroup();
					CampaignAttacker( EASY, 3, HUNTRESS );
					CampaignAttacker( EASY, 2, ANCIENT_PROTECT );
					MikesSuicide(4*60,4*60,4*60,user);
					//*** WAVE 10 ***
					InitAssaultGroup();
					CampaignAttacker( EASY, 4, ARCHER );
					CampaignAttacker( EASY, 2, HUNTRESS );
					CampaignAttacker( EASY, 1, BALLISTA );
					CampaignAttacker( EASY, 2, WISP );
					MikesSuicide(6*60,6*60,6*60,user);
					//*** WAVE 11 ***
					InitAssaultGroup();
					CampaignAttacker( EASY, 2, ARCHER );
					CampaignAttacker( EASY, 1, HUNTRESS );
					CampaignAttacker( EASY, 1, ANCIENT_PROTECT );
					CampaignAttacker( EASY, 1, WISP );
					MikesSuicide(2*60,2*60,2*60,user);
					//*** WAVE 12 ***
					InitAssaultGroup();
					CampaignAttacker( EASY, 6, ARCHER );
					CampaignAttacker( EASY, 1, BALLISTA );
					MikesSuicide(4*60,4*60,4*60,user);
				}
			}

		} // class o05_yellow_ai 

	}

