// Generated by .


	public partial class GameDefine 
	{

		public class o05_teal_ai
		{
		//============================================================================
		//  Orc 05 -- Cenarius -- AI Script
		//============================================================================
		//============================================================================
		// Cenarius uses Command 5 to defend a town, Command 6 to retreat to his base.
		//
		// Prior to using Command 6, Commands 3 & 4 must be used to init the home base 
		// coords. This only needs to be done once at the start of the level.
		//
		// Prior to using Command 5, Commands 1 & 2 must be used to set up goal 
		// coordinates. This should be done each time Command 5 is used, since the 
		// goal will be changing throughout the level.
		//============================================================================
		//============================================================================
		//  gather_force 
		//============================================================================
			public void gather_force(  )
			{
				// Original JassCode
				Trace("Cenarius gather_force\n");
				InitAssaultGroup();
				SetAssaultGroup( 1,1,CENARIUS );
				SetAssaultGroup( 2,99,ARCHER );
				SetAssaultGroup( 2,99,HUNTRESS );
				SetInitialWave(1);
				FormGroup(1,true);
				Trace("Cenarius force ready\n");
			}

		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				int command;
				int data;
				double goal_x = 0;
				double goal_y = 0;
				double home_x = 0;
				double home_y = 0;
				CampaignAI(MOON_WELL,null);
				SetBuildUnit( 2, ARCHER );
				SetBuildUnit( 2, HUNTRESS );
				campaign_wood_peons = 0;
				while( true )
				{
					while( true )
					{
						if(  CommandsWaiting() != 0 )
							break;
						Sleep(0.5);
					}
					command = GetLastCommand();
					data = GetLastData();
					PopLastCommand();
					//--------------------------------------------------------------------
					//*** SET GOAL X
					//--------------------------------------------------------------------
					if(  command==1  )
					{
						Trace("Cenarius set goal x\n");
						goal_x = data;
						//--------------------------------------------------------------------
						//*** SET GOAL Y
						//--------------------------------------------------------------------
					}
					else if(  command==2  )
					{
						Trace("Cenarius set goal y\n");
						goal_y = data;
						//--------------------------------------------------------------------
						//*** SET GOAL X
						//--------------------------------------------------------------------
					}
					else if(  command==3  )
					{
						Trace("Cenarius set home x\n");
						home_x = data;
						//--------------------------------------------------------------------
						//*** SET GOAL Y
						//--------------------------------------------------------------------
					}
					else if(  command==4  )
					{
						Trace("Cenarius set home y\n");
						home_y = data;
						//--------------------------------------------------------------------
						//*** ATTACK GOAL
						//--------------------------------------------------------------------
					}
					else if(  command==5  )
					{
						Trace("Cenarius attack goal\n");
						gather_force();
						Trace("Cenarius home change & attack order\n");
						SetCaptainHome(ATTACK_CAPTAIN, goal_x, goal_y);
						CaptainAttack(goal_x,goal_y);
						//--------------------------------------------------------------------
						//*** GO HOME
						//--------------------------------------------------------------------
					}
					else if(  command==6  )
					{
						Trace("Cenarius home change & go home order\n");
						SetCaptainHome(ATTACK_CAPTAIN, home_x, home_y);
						ClearCaptainTargets();
						CaptainGoHome();
					}
				}
			}

		} // class o05_teal_ai 

	}

