// Generated by .


	public partial class GameDefine 
	{

		public class o08_purple_ai
		{
		//============================================================================
		//  Orc 08 -- purple player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(0);
			public BJPlayer  jaina = Player(9);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(BURROW,null);
				SetReplacements(1,1,3);
				do_campaign_farms = false;
				SetBuildUnitEx ( 0,0,1, GREAT_HALL );
				SetBuildUnit ( 1, CHAOS_PEON );
				SetBuildUnitEx ( 0,0,1, ORC_BARRACKS );
				SetBuildUnitEx ( 0,0,5, BURROW );
				SetBuildUnitEx ( 0,0,1, FORGE );
				SetBuildUnit ( 8, CHAOS_PEON );
				SetBuildUnitEx ( 0,0,1, STRONGHOLD );
				SetBuildUnitEx ( 0,0,1, BESTIARY );
				SetBuildUnitEx ( 0,0,1, LODGE );
				CampaignDefenderEx( 0,0,1, CHAOS_GRUNT );
				CampaignDefenderEx( 0,0,1, CHAOS_WARLOCK );
				CampaignDefenderEx( 1,1,0, CHAOS_RAIDER );
				SetBuildUpgrEx( 3,3,3, UPG_ORC_SPIKES );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_BERSERK );
				SetBuildUpgr ( 1, UPG_ORC_ENSNARE );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, CHAOS_GRUNT );
				SuicideOnPlayer(M3,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, CHAOS_GRUNT );
				CampaignAttackerEx( 2,2,3, CHAOS_RAIDER );
				SuicideOnPlayerEx(M10,M10,M9,jaina);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,3, CHAOS_GRUNT );
				CampaignAttackerEx( 1,1,2, CHAOS_RAIDER );
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M7,M7,M6,user);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, CHAOS_GRUNT );
				CampaignAttackerEx( 1,1,1, CHAOS_KODO );
				CampaignAttackerEx( 1,1,2, CATAPULT );
				SuicideOnPlayerEx(M6,M6,M7,jaina);
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, CHAOS_RAIDER );
				CampaignAttackerEx( 2,2,3, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M7,M7,M6,user);
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttackerEx( 6,6,7, CHAOS_GRUNT );
				CampaignAttackerEx( 1,1,2, CATAPULT );
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M6,M6,M7,jaina);
				//*** WAVE 7 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,7, CHAOS_RAIDER );
				CampaignAttackerEx( 1,1,1, CHAOS_KODO );
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M7,M7,M6,user);
				//*** WAVE 8 ***
				InitAssaultGroup();
				CampaignAttackerEx( 7,7,9, CHAOS_GRUNT );
				CampaignAttackerEx( 2,2,3, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M6,M6,M7,jaina);
				//*** WAVE 9 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,5, CHAOS_GRUNT );
				CampaignAttackerEx( 1,1,2, CATAPULT );
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M7,M7,M6,user);
				//*** WAVE 10 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, CHAOS_GRUNT );
				CampaignAttackerEx( 3,3,4, CHAOS_RAIDER );
				CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
				SuicideOnPlayerEx(M6,M6,M7,jaina);
				while( true )
				{
					//*** WAVE 11 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,5, CHAOS_GRUNT );
					CampaignAttackerEx( 1,1,2, CHAOS_KODO );
					CampaignAttackerEx( 1,1,2, CATAPULT );
					CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
					SuicideOnPlayerEx(M7,M7,M6,user);
					//*** WAVE 12 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, CHAOS_GRUNT );
					CampaignAttackerEx( 3,3,4, CHAOS_RAIDER );
					CampaignAttackerEx( 1,1,2, CHAOS_WARLOCK );
					SuicideOnPlayerEx(M6,M6,M7,jaina);
					//*** WAVE 13 ***
					InitAssaultGroup();
					CampaignAttackerEx( 5,5,8, CHAOS_RAIDER );
					SuicideOnPlayerEx(M7,M7,M6,user);
					//*** WAVE 14+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 6,6,8, CHAOS_GRUNT );
					CampaignAttackerEx( 3,3,4, CHAOS_WARLOCK );
					SuicideOnPlayerEx(M6,M6,M7,jaina);
				}
			}

		} // class o08_purple_ai 

	}

