// Generated by .


	public partial class GameDefine 
	{

		public class o08_Jaina_ai
		{
		//============================================================================
		//  Orc 08 -- Jaina -- AI Script
		//============================================================================
			public BJPlayer  purple = Player(3);
			public BJPlayer  green = Player(10);
		//============================================================================
		//  assaults
		//============================================================================
			public void assaults(  )
			{
				// Original JassCode
				int target;
				int strength = 1;
				while( true )
				{
					while( true )
					{
						if(  CommandsWaiting() != 0 )
							break;
						Sleep(5);
					}
					if(  strength == 1  )
					{
						CampaignAttackerEx ( 4,4,3, FOOTMAN );
						CampaignAttackerEx ( 2,2,2, RIFLEMAN );
					}
					else if(  strength == 2  )
					{
						CampaignAttackerEx ( 4,4,2, FOOTMAN );
						CampaignAttackerEx ( 4,4,4, RIFLEMAN );
					}
					else
					{
						CampaignAttackerEx ( 2,2,4, FOOTMAN );
						CampaignAttackerEx ( 3,3,2, RIFLEMAN );
						CampaignAttackerEx ( 1,1,1, KNIGHT );
						CampaignAttackerEx ( 1,1,0, SORCERESS );
					}
					strength = strength + 1;
					target = GetLastCommand();
					PopLastCommand();
					SuicideOnPlayer(M3,Player(target));
				}
			}

		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				//call SetCaptainChanges(false)
				// disable certain campaign behaviors
				// (mostly to make Jaina appear more intelligent)
				//
				//call SetHeroesFlee(true)
				//call SetUnitsFlee(true)
				//call SetGroupsFlee(true)
				SetSlowChopping(false);
				campaign_wood_peons = 7;
				// define basic tech tree buildings required
				//
				SetBuildUnit( 1, PEASANT );
				SetBuildUnit( 1, TOWN_HALL );
				SetBuildUnit( 2, PEASANT );
				SetBuildUnit( 1, BARRACKS );
				SetBuildUnit( 1, BLACKSMITH );
				SetBuildUnit( 1, KEEP );
				SetBuildUnit( 1, HUMAN_ALTAR );
				SetBuildUnit( 1, SANCTUM );
				SetBuildUnit( 1, CASTLE );
				SetBuildUnit( 12, PEASANT );
				CampaignDefenderEx( 1,1,1, FOOTMAN );
				CampaignDefenderEx( 1,1,1, SORCERESS );
				CampaignDefenderEx( 1,1,0, KNIGHT );
				CampaignDefenderEx( 1,1,0, RIFLEMAN );
				CampaignDefenderEx( 1,1,1, JAINA );
				SetBuildUpgrEx( 2,2,1, UPG_MELEE );
				SetBuildUpgrEx( 2,2,1, UPG_RANGED );
				SetBuildUpgrEx( 2,2,1, UPG_ARMOR );
				SetBuildUpgrEx( 2,2,1, UPG_LEATHER );
				SetBuildUpgrEx( 2,2,1, UPG_MASONRY );
				SetBuildUpgrEx( 1,1,0, UPG_DEFEND );
				SetBuildUpgrEx( 1,1,0, UPG_BREEDING );
				SetBuildUpgrEx( 2,2,1, UPG_PRAYING );
				SetBuildUpgrEx( 2,2,1, UPG_SORCERY );
				SetBuildUpgrEx( 1,1,1, UPG_GUN_RANGE );
				SetBuildUpgrEx( 1,1,0, UPG_BOMBS );
				SetBuildUpgrEx( 1,1,0, UPG_HAMMERS );
				assaults();
			}

		} // class o08_Jaina_ai 

	}

