// Generated by .


	public partial class GameDefine 
	{

		public class o08_green_ai
		{
		//============================================================================
		//  Orc 8 -- green player -- AI Script
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(BURROW,null);
				SuicideUnits( INFERNAL, 0, 0, 0, 0, 0, 0, 0, 0, 0 );
			}

		} // class o08_green_ai 

	}

