// Generated by .


	public partial class GameDefine 
	{

		public class o08_VsPlayer_ai
		{
		//============================================================================
		//  Orc 8 -- Infernals Vs. User -- AI Script
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(BURROW,null);
				while( true )
				{
					SuicideUnitEx( 1, INFERNAL, 0 );
					Sleep(1);
				}
			}

		} // class o08_VsPlayer_ai 

	}

