// Generated by .


	public partial class GameDefine 
	{

		public class orc03purple_ai
		{
		//============================================================================
		//  Orc 3 -- purple player -- AI Script
		//============================================================================
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(0, null);
				SetBuildUnit( 1, PEASANT );
				SetBuildUnit( 1, TOWN_HALL );
				SetBuildUnit( 2, PEASANT );
				SetBuildUnit( 1, BARRACKS );
				SetBuildUnit( 1, BLACKSMITH );
				SetBuildUnit( 4, RIFLEMEN );
				SetBuildUnit( 1, KEEP );
				SetBuildUnit( 1, WORKSHOP );
				SetBuildUnit( 1, MORTAR );
				SetBuildUnit( 3, PEASANT );
				SetAssaultGroup( 4, 4, RIFLEMEN );
				SetAssaultGroup( 1, 1, MORTAR );
				SuicideOnPlayer(1*60,Player(0));
				while( true )
				{
					SuicideOnPlayer(8*60,Player(0));
				}
			}

		} // class orc03purple_ai 

	}

