// Generated by .


	public partial class GameDefine 
	{

		public class orc03warsong_ai
		{
		//============================================================================
		//  Orc 3 -- Warsong Ally -- AI Script
		//============================================================================
			public int heroes(  )
			{
				// Original JassCode
				int level = GetHeroLevelAI();
				if(  level == 2 || level == 3 || level == 7  )
				{
					// critical strike
					return UnitId( "AOcr" );
				}
				if(  level == 4 || level == 6 || level == 8  )
				{
					// mirror image
					return UnitId( "AOmi" );
				}
				if(  level == 5  )
				{
					// whirlwind
					return UnitId( "AOww" );
				}
				// wind walk
				return UnitId( "AOwk" );
			}

		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(0, heroes);
				SetBuildUnit( 1, PEON );
				SetBuildUnit( 1, GREAT_HALL );
				SetBuildUnit( 1, STRONGHOLD );
				SetBuildUnit( 1, ORC_ALTAR );
				SetBuildUnit( 1, BLADE_MASTER );
				SetBuildUnit( 1, ORC_BARRACKS );
				SetBuildUnit( 4, GRUNT );
				SetBuildUnit( 3, PEON );
				SetAssaultGroup( 1, 1, BLADE_MASTER );
				SetAssaultGroup( 4, 4, GRUNT );
				SuicideOnPlayer(0,Player(1));
				SuicideOnPlayer(7*60,Player(3));
				SuicideOnPlayer(8*60,Player(2));
				SuicideOnPlayer(9*60,Player(9));
				SleepForever();
			}

		} // class orc03warsong_ai 

	}

