// Generated by .


	public partial class GameDefine 
	{

		public class orc03blue_ai
		{
		//============================================================================
		//  Orc 3 -- blue player -- AI Script
		//============================================================================
			public int heroes(  )
			{
				// Original JassCode
				int level = GetHeroLevelAI();
				if(  level == 2 || level == 6 || level == 9  )
				{
					// elemental
					return UnitId( "AHwe" );
				}
				if(  level == 3 || level == 5 || level == 8  )
				{
					// blizzard
					return UnitId( "AHbz" );
				}
				if(  level == 7  )
				{
					// mass teleport
					return UnitId( "AHmt" );
				}
				// brilliance aura
				return UnitId( "AHab" );
			}

		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				// error 0 ??
				CampaignAI( 0 , heroes);
				SetBuildUnit( 1, PEASANT );
				SetBuildUnit( 1, TOWN_HALL );
				SetBuildUnit( 1, KEEP );
				SetBuildUnit( 1, HUMAN_ALTAR );
				SetBuildUnit( 1, ARCHMAGE );
				SetBuildUnit( 1, BARRACKS );
				SetBuildUnit( 2, FOOTMEN );
				SetBuildUnit( 1, BLACKSMITH );
				SetBuildUnit( 2, RIFLEMEN );
				SetBuildUnit( 1, CHURCH );
				SetBuildUnit( 1, PRIEST );
				SetBuildUnit( 3, PEASANT );
				SetAssaultGroup( 1, 1, ARCHMAGE );
				SetAssaultGroup( 2, 2, FOOTMEN );
				SetAssaultGroup( 2, 2, RIFLEMEN );
				SetAssaultGroup( 1, 1, PRIEST );
				SuicideOnPlayer(1*60,Player(0));
				while( true )
				{
					SuicideOnPlayer(9*60,Player(0));
				}
			}

		} // class orc03blue_ai 

	}

