// Generated by .


	public partial class GameDefine 
	{

		public class SleepForever_ai
		{
			public void main(  )
			{
				// Original JassCode
				SleepForever();
			}

		} // class SleepForever_ai 

	}

