// Generated by .


	public partial class GameDefine 
	{

		public class u02_blue_ai
		{
		//============================================================================
		//  Undead 02 -- Blue player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				do_debug_cheats = true;
				CampaignAI(HOUSE,null);
				SetReplacements(1,1,3);
				CampaignDefenderEx(1,1,3, FOOTMAN );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,6, FOOTMEN );
				SuicideOnPlayer(0,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,7, FOOTMEN );
				SuicideOnPlayer(M3,user);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,6, FOOTMEN );
				SuicideOnPlayer(M3,user);
				while( true )
				{
					//*** WAVE 4 ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,7, FOOTMEN );
					SuicideOnPlayer(M3,user);
					//*** WAVE 5 ***
					InitAssaultGroup();
					CampaignAttackerEx( 4,4,6, FOOTMEN );
					SuicideOnPlayer(M3,user);
				}
			}

		} // class u02_blue_ai 

	}

