// Generated by .


	public partial class GameDefine 
	{

		public class u03_teal_ai
		{
		//============================================================================
		//  Undead 03 -- teal player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ELF_FARM,null);
				SetReplacements(1,1,3);
				do_campaign_farms = false;
				SetBuildUnitEx( 0,0,1, TOWN_HALL );
				SetBuildUnitEx( 2,2,2, PEASANT );
				SetBuildUnitEx( 0,0,1, ELF_HIGH_BARRACKS );
				SetBuildUnitEx( 3,3,3, PEASANT );
				SetBuildUnitEx( 0,0,1, LUMBER_MILL );
				SetBuildUnitEx( 0,0,1, BLACKSMITH );
				SetBuildUnitEx( 0,0,1, KEEP );
				SetBuildUnitEx( 0,0,1, SANCTUM );
				CampaignDefenderEx( 1,1,2, HIGH_SWORDMAN );
				CampaignDefenderEx( 0,0,5, HIGH_ARCHER );
				CampaignDefenderEx( 1,1,2, PRIEST );
				SleepForever();
			}

		} // class u03_teal_ai 

	}

