// Generated by .


	public partial class GameDefine 
	{

		public class u04b_lightblue_ai
		{
		//============================================================================
		//  Undead 04B -- light blue player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ELF_FARM,null);
				SetReplacements(0,1,3);
				SetBuildUnitEx( 0,0,1, TOWN_HALL );
				SetBuildUnitEx( 2,2,2, PEASANT );
				SetBuildUnitEx( 0,0,1, ELF_HIGH_BARRACKS );
				SetBuildUnitEx( 2,2,2, ZEPPLIN );
				SetBuildUnitEx( 0,0,1, LUMBER_MILL );
				SetBuildUnitEx( 0,0,9, ELF_FARM );
				SetBuildUnitEx( 5,5,5, PEASANT );
				SetBuildUnitEx( 0,0,1, KEEP );
				SetBuildUnitEx( 0,0,1, SANCTUM );
				SetBuildUnitEx( 0,0,1, CASTLE );
				CampaignDefenderEx( 1,1,3, HIGH_FOOTMAN );
				CampaignDefenderEx( 1,1,4, HIGH_ARCHER );
				CampaignDefenderEx( 0,0,1, PRIEST );
				CampaignDefenderEx( 1,1,3, DRAGON_HAWK );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,3, DRAGON_HAWK );
				SuicideOnPlayerEx(M5,M4,M1,user);
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,4,5, DRAGON_HAWK );
				SuicideOnPlayerEx(M8,M6,M3,user);
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,4,5, DRAGON_HAWK );
				CampaignAttackerEx( 2,3,4, HIGH_ARCHER );
				SuicideOnPlayerEx(M8,M6,M3,user);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,5,8, DRAGON_HAWK );
				SuicideOnPlayerEx(M8,M6,M3,user);
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,3,4, HIGH_FOOTMAN );
				CampaignAttackerEx( 1,3,4, HIGH_ARCHER );
				CampaignAttackerEx( 1,3,6, DRAGON_HAWK );
				SuicideOnPlayerEx(M8,M6,M3,user);
				while( true )
				{
					//*** WAVE 6+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,5,9, DRAGON_HAWK );
					SuicideOnPlayerEx(M8,M6,M3,user);
					//*** WAVE 7+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 1,1,3, HIGH_FOOTMAN );
					CampaignAttackerEx( 2,2,2, HIGH_ARCHER );
					CampaignAttackerEx( 1,3,6, DRAGON_HAWK );
					CampaignAttackerEx( 0,1,2, BALLISTA );
					SuicideOnPlayerEx(M8,M6,M3,user);
					//*** WAVE 8+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 1,3,6, DRAGON_HAWK );
					CampaignAttackerEx( 1,3,3, HIGH_ARCHER );
					CampaignAttackerEx( 1,1,2, PRIEST );
					SuicideOnPlayerEx(M8,M6,M3,user);
				}
			}

		} // class u04b_lightblue_ai 

	}

