// Generated by .


	public partial class GameDefine 
	{

		public class u04x02_ai
		{
		//============================================================================
		//  $Id: u04x02.ai,v 1.9 2003/04/29 23:06:48 rpardo Exp $
		//============================================================================
			public BJPlayer  user = PlayerEx(4);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SetReplacements(1,1,3);
				CampaignDefenderEx( 1,1,2, HIGH_SWORDMAN );
				SleepForever();
			}

		} // class u04x02_ai 

	}

