// Generated by .


	public partial class GameDefine 
	{

		public class u04x08_ai
		{
		//============================================================================
		//  $Id: u04x08.ai,v 1.1.2.2 2003/05/10 10:19:22 abond Exp $
		//============================================================================
			// First Camp
			// lvl 1
			public int NSPIDERLING = UnitId( "nspd" );
			// lvl 3
			public int NWARRIOR = UnitId( "nnwa" );
			// Second Camp
			// lvl 1
			public int NWEBSPIDERLING = UnitId( "n00I" );
			// lvl 5
			public int NSPIDER = UnitId( "n00G" );
			// Final Camp
			// lvl 1
			public int NSPIDERLING02 = UnitId( "n00J" );
			// lvl 3
			public int NWARRIOR02 = UnitId( "n00K" );
			//constant integer NSEER          = 'nnwr' // lvl 5
			//constant integer NLORD          = 'nnws' // lvl 7
			//constant integer NQUEEN         = 'nnwq' // lvl 9
			//constant integer NWEBSPINNER    = 'nnwl' // lvl 3
			//constant integer NSEERHARD      = 'n00H' // lvl 8
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SetReplacements(10,10,99);
				SleepForever();
			}

		} // class u04x08_ai 

	}

