// Generated by .


	public partial class GameDefine 
	{

		public class u05_blue_ai
		{
		//============================================================================
		//  Undead 05 -- blue player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ELF_FARM,null);
				do_campaign_farms = false;
				SetReplacements(1,1,3);
				SetBuildUnitEx( 0,0,1, TOWN_HALL );
				SetBuildUnitEx( 2,2,2, PEASANT );
				SetBuildUnitEx( 0,0,1, ELF_HIGH_BARRACKS );
				SetBuildUnitEx( 0,0,8, ELF_FARM );
				SetBuildUnitEx( 5,5,5, PEASANT );
				CampaignDefenderEx( 1,1,1, HIGH_SWORDMAN );
				CampaignDefenderEx( 1,1,1, HIGH_ARCHER );
				CampaignDefenderEx( 0,0,1, SORCERESS );
				CampaignDefenderEx( 0,0,1, SYLVANUS );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 1,1,2, HIGH_SWORDMAN );
				CampaignAttackerEx( 2,2,4, HIGH_ARCHER );
				SuicideOnPlayer(0,user);
				SetBuildUpgrEx( 1,1,1, UPG_SORCERY );
				SetBuildUpgrEx( 1,1,1, UPG_PRAYING );
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 1,1,3, HIGH_SWORDMAN );
				CampaignAttackerEx( 3,3,3, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,1, SYLVANUS );
				SuicideOnPlayerEx(M6,M6,M5,user);
				SetBuildUpgrEx( 1,1,1, UPG_DEFEND );
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 1,1,4, HIGH_SWORDMAN );
				CampaignAttackerEx( 3,3,4, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,1, PRIEST );
				CampaignAttackerEx( 0,0,1, SORCERESS );
				CampaignAttackerEx( 1,1,2, BALLISTA );
				SuicideOnPlayerEx(M7,M7,M4,user);
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,4, HIGH_SWORDMAN );
				CampaignAttackerEx( 2,2,4, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,1, PRIEST );
				CampaignAttackerEx( 1,1,1, SYLVANUS );
				SuicideOnPlayerEx(M7,M7,M5,user);
				SetBuildUpgrEx( 0,0,2, UPG_SORCERY );
				SetBuildUpgrEx( 0,0,2, UPG_PRAYING );
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, HIGH_SWORDMAN );
				CampaignAttackerEx( 3,3,4, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,2, PRIEST );
				CampaignAttackerEx( 0,0,1, SORCERESS );
				CampaignAttackerEx( 0,0,1, SYLVANUS );
				CampaignAttackerEx( 1,1,1, BALLISTA );
				SuicideOnPlayerEx(M6,M6,M4,user);
				while( true )
				{
					//*** WAVE 6+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,2, HIGH_SWORDMAN);
					CampaignAttackerEx( 5,5,7, HIGH_ARCHER );
					CampaignAttackerEx( 1,1,2, PRIEST );
					CampaignAttackerEx( 1,1,1, SORCERESS );
					CampaignAttackerEx( 1,1,1, SYLVANUS );
					SuicideOnPlayerEx(M7,M7,M5,user);
					//*** WAVE 7+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 4,4,4, HIGH_SWORDMAN);
					CampaignAttackerEx( 2,2,2, HIGH_ARCHER );
					CampaignAttackerEx( 3,3,4, PRIEST );
					CampaignAttackerEx( 0,0,1, SORCERESS );
					CampaignAttackerEx( 1,1,2, BALLISTA );
					SuicideOnPlayerEx(M6,M6,M4,user);
					//*** WAVE 8+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,3, HIGH_SWORDMAN);
					CampaignAttackerEx( 3,3,3, HIGH_ARCHER );
					CampaignAttackerEx( 1,1,2, PRIEST );
					CampaignAttackerEx( 2,2,2, SORCERESS );
					CampaignAttackerEx( 1,1,1, SYLVANUS );
					SuicideOnPlayerEx(M7,M7,M5,user);
				}
			}

		} // class u05_blue_ai 

	}

