// Generated by .


	public partial class GameDefine 
	{

		public class u05_brown_ai
		{
		//============================================================================
		//  Undead 05 -- brown player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ELF_FARM,null);
				do_campaign_farms = false;
				SetReplacements(1,1,3);
				SetCaptainHome(BOTH_CAPTAINS,-4963,-5986);
				SetBuildUnitEx( 0,0,1, TOWN_HALL );
				SetBuildUnitEx( 2,2,2, PEASANT );
				SetBuildUnitEx( 0,0,1, HUMAN_ALTAR );
				SetBuildUnitEx( 0,0,1, KEEP );
				SetBuildUnitEx( 0,0,1, CASTLE );
				CampaignDefenderEx( 1,1,1, HIGH_SWORDMAN );
				CampaignDefenderEx( 0,0,1, HIGH_ARCHER );
				CampaignDefenderEx( 0,0,1, PRIEST );
				CampaignDefenderEx( 0,0,1, SORCERESS );
				CampaignDefenderEx( 1,1,2, DRAGON_HAWK );
				SetBuildUpgrEx( 1,1,2, UPG_SORCERY );
				SetBuildUpgrEx( 1,1,2, UPG_PRAYING );
				SleepForever();
			}

		} // class u05_brown_ai 

	}

