// Generated by .


	public partial class GameDefine 
	{

		public class u06_red_ai
		{
		//============================================================================
		//  Undead 06 -- red player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(PIG_FARM,null);
				SetReplacements(1,1,3);
				SetBuildUnitEx ( 0,0,1, GREAT_HALL );
				SetBuildUnit ( 1, PEON );
				SetBuildUnitEx ( 0,0,2, ORC_BARRACKS );
				SetBuildUnit ( 8, PEON );
				CampaignDefenderEx( 1,1,2, GRUNT );
				CampaignDefenderEx( 1,1,1, ORC_DRAGON );
				CampaignDefenderEx( 1,1,1, W2_WARLOCK );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_RANGED );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_MELEE );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_SPIKES );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_BERSERK );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_ENSNARE );
				WaitForSignal();
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 1,1,2, ORC_DRAGON );
				SuicideOnPlayerEx(M1,M1,0,user);
				SetBuildUpgrEx( 0,0,1, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 1,1,2, UPG_ORC_RANGED );
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,4, GRUNT );
				CampaignAttackerEx( 1,1,2, ORC_DRAGON );
				SuicideOnPlayerEx(M10,M10,M8,user);
				SetBuildUpgrEx( 1,1,2, UPG_ORC_MELEE );
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 1,1,2, ORC_DRAGON );
				SuicideOnPlayerEx(M10,M10,M8,user);
				SetBuildUpgrEx( 1,1,2, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 1,1,2, UPG_ORC_SPIKES );
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, RAIDER );
				CampaignAttackerEx( 1,1,2, ORC_DRAGON );
				CampaignAttackerEx( 1,1,2, W2_WARLOCK );
				SuicideOnPlayerEx(M10,M10,M8,user);
				SetBuildUpgrEx( 0,0,3, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 0,0,3, UPG_ORC_RANGED );
				SetBuildUpgrEx( 0,0,3, UPG_ORC_MELEE );
				SetBuildUpgrEx( 0,0,3, UPG_ORC_SPIKES );
				while( true )
				{
					//*** WAVE 5+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 1,1,2, ORC_DRAGON );
					SuicideOnPlayerEx(M10,M10,M8,user);
					//*** WAVE 6+ ***
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, RAIDER );
					CampaignAttackerEx( 1,1,2, ORC_DRAGON );
					CampaignAttackerEx( 1,1,2, HEAD_HUNTER );
					SuicideOnPlayerEx(M10,M10,M8,user);
				}
			}

		} // class u06_red_ai 

	}

