// Generated by .


	public partial class GameDefine 
	{

		public class u06_blue_ai
		{
		//============================================================================
		//  Undead 06 -- blue player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(PIG_FARM,null);
				SetReplacements(1,1,3);
				SetBuildUnitEx ( 0,0,1, GREAT_HALL );
				SetBuildUnit ( 1, PEON );
				SetBuildUnitEx ( 0,0,1, ORC_BARRACKS );
				SetBuildUnit ( 8, PEON );
				CampaignDefenderEx( 1,1,3, HEAD_HUNTER );
				CampaignDefenderEx( 0,0,2, GRUNT );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_RANGED );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_MELEE );
				SetBuildUpgrEx( 0,0,1, UPG_ORC_SPIKES );
				SleepForever();
			}

		} // class u06_blue_ai 

	}

