// Generated by .


	public partial class GameDefine 
	{

		public class u06x03_ai
		{
		//============================================================================
		//  $Id
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetReplacements(1,1,3);
				campaign_wood_peons = 2;
				SetBuildUnit( 1, ACOLYTE );
				CampaignDefenderEx( 1, 1, 3, GHOUL );
				SleepForever();
			}

		} // class u06x03_ai 

	}

