// Generated by .


	public partial class GameDefine 
	{

		public class u06x07_ai
		{
		//==================================================================================================
		//  $Id: u06x07.ai,v 1.10.2.2 2003/05/12 20:47:05 abond Exp $
		//==================================================================================================
			public int LICH2 = UnitId( "U001" );
			public BJPlayer  user = PlayerEx(9);
		//--------------------------------------------------------------------------------------------------
		//  main
		//--------------------------------------------------------------------------------------------------
			public void main(  )
			{
				// Original JassCode
				CampaignAI(ZIGGURAT_1,null);
				SetReplacements(2,2,3);
				SetWoodPeons(2);
				SetBuildUnitEx( 1, 1, 1, ACOLYTE );
				SetBuildUnitEx( 0, 0, 1, NECROPOLIS_1 );
				SetBuildUnitEx( 0, 0, 1, UNDEAD_MINE );
				SetBuildUnitEx( 0, 0, 1, CRYPT );
				SetBuildUnitEx( 0, 0, 3, ZIGGURAT_1 );
				SetBuildUnitEx( 0, 0, 1, GRAVEYARD );
				SetBuildUnitEx( 0, 0, 1, UNDEAD_ALTAR );
				SetBuildUnitEx( 0, 0, 1, NECROPOLIS_2 );
				SetBuildUnitEx( 0, 0, 3, ZIGGURAT_2 );
				SetBuildUnitEx( 0, 0, 1, SLAUGHTERHOUSE );
				SetBuildUnitEx( 0, 0, 1, SAC_PIT );
				SetBuildUnitEx( 0, 0, 1, NECROPOLIS_3 );
				SetBuildUnitEx( 0, 0, 1, BONEYARD );
				SetBuildUnitEx( 5, 5, 5, ACOLYTE );
				CampaignDefenderEx( 0, 0, 1, LICH2 );
				CampaignDefenderEx( 1, 1, 1, ABOMINATION );
				CampaignDefenderEx( 1, 1, 1, FROST_WYRM );
				CampaignDefenderEx( 1, 1, 1, NECRO );
				SetBuildUpgrEx( 1,1,1, UPG_BLK_SPHINX );
				SetBuildUpgrEx( 1,1,1, UPG_EXHUME );
				SetBuildUpgrEx( 0,0,1, UPG_GHOUL_FRENZY);
				SetBuildUpgrEx( 1,1,1, UPG_FIEND_WEB );
				SetBuildUpgrEx( 1,1,1, UPG_SKEL_LIFE );
				SetBuildUpgrEx( 0,0,1, UPG_SKEL_MASTERY);
				SetBuildUpgrEx( 0,0,1, UPG_NECROS );
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,5, ABOMINATION );
				SuicideOnPlayerEx(M3,M3,M2,user);
				SetBuildUpgrEx( 0,0,1, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 0,1,1, UPG_CR_ATTACK );
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,4, GARGOYLE );
				CampaignAttackerEx( 0,0,1, FROST_WYRM );
				SuicideOnPlayerEx(M7,M7,M6,user);
				SetBuildUpgrEx( 0,0,1, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 0,0,1, UPG_CR_ARMOR );
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,4, ABOMINATION );
				CampaignAttackerEx( 2,2,5, NECRO );
				CampaignAttackerEx( 1,1,1, LICH2 );
				SuicideOnPlayerEx(M6,M6,M5,user);
				SetBuildUpgrEx( 0,0,1, UPG_PLAGUE );
				SetBuildUpgrEx( 1,1,1, UPG_GHOUL_FRENZY);
				SetBuildUpgrEx( 1,1,1, UPG_WYRM_BREATH );
				SetBuildUpgrEx( 1,1,1, UPG_SKEL_MASTERY);
				SetBuildUpgrEx( 1,1,2, UPG_NECROS );
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, ABOMINATION );
				CampaignAttackerEx( 3,3,5, CRYPT_FIEND );
				CampaignAttackerEx( 1,1,2, MEAT_WAGON );
				SuicideOnPlayerEx(M7,M7,M6,user);
				SetBuildUpgrEx( 1,1,2, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 1,1,2, UPG_CR_ATTACK );
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,3, GARGOYLE );
				CampaignAttackerEx( 1,1,2, FROST_WYRM );
				SuicideOnPlayerEx(M6,M6,M5,user);
				SetBuildUpgrEx( 1,1,2, UPG_UNHOLY_ARMOR);
				SetBuildUpgrEx( 1,1,2, UPG_CR_ARMOR );
				SetBuildUpgrEx( 2,2,2, UPG_NECROS );
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, NECRO );
				CampaignAttackerEx( 2,2,2, MEAT_WAGON );
				CampaignAttackerEx( 1,1,1, LICH2 );
				SuicideOnPlayerEx(M7,M7,M6,user);
				SetBuildUpgrEx( 2,2,3, UPG_UNHOLY_STR );
				SetBuildUpgrEx( 2,2,3, UPG_CR_ATTACK );
				SetBuildUpgrEx( 1,1,1, UPG_GHOUL_FRENZY);
				SetBuildUpgrEx( 1,1,1, UPG_PLAGUE );
				//*** WAVE 7+ ***
				while( true )
				{
					InitAssaultGroup();
					CampaignAttackerEx( 6,6,8, ABOMINATION );
					CampaignAttackerEx( 2,2,3, CRYPT_FIEND );
					SuicideOnPlayerEx(M7,M7,M6,user);
					InitAssaultGroup();
					CampaignAttackerEx( 3,3,4, GARGOYLE );
					CampaignAttackerEx( 2,2,3, FROST_WYRM );
					SuicideOnPlayerEx(M7,M7,M6,user);
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,3, ABOMINATION );
					CampaignAttackerEx( 2,2,4, NECRO );
					CampaignAttackerEx( 1,1,2, MEAT_WAGON );
					CampaignAttackerEx( 1,1,1, LICH2 );
					SuicideOnPlayerEx(M7,M7,M6,user);
				}
			}

		} // class u06x07_ai 

	}

