// Generated by .


	public partial class GameDefine 
	{

		public class u08_blue_ai
		{
		//============================================================================
		//  Undead 08 -- Blue (Grey) player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
			public BJPlayer  kel = Player(6);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				do_campaign_farms = false;
				SetCaptainHome(ATTACK_CAPTAIN,2963,4429);
				SetBuildUnit( 1, TOWN_HALL );
				SetBuildUnit( 2, PEASANT );
				SetBuildUnit( 2, BARRACKS );
				SetBuildUnit( 1, LUMBER_MILL );
				SetBuildUnit( 1, BLACKSMITH );
				SetBuildUnit( 5, PEASANT );
				SetBuildUnit( 6, HOUSE );
				SetBuildUnit( 1, WORKSHOP );
				SetBuildUnit( 1, KEEP );
				SetBuildUnit( 1, SANCTUM );
				SetBuildUnit( 1, HUMAN_ALTAR );
				SetBuildUnit( 1, CASTLE );
				SetBuildUnit( 3, AVIARY );
				SetBuildUnit( 1, WATCH_TOWER );
				SetBuildUnit( 2, CANNON_TOWER );
				SetBuildUnit( 1, GUARD_TOWER );
				CampaignDefender (EASY, 1, FOOTMAN );
				CampaignDefender (EASY, 1, KNIGHT );
				CampaignDefender (EASY, 1, RIFLEMAN );
				CampaignDefender (EASY, 2, GRYPHON );
				CampaignDefender (EASY, 1, ARCHMAGE );
				SetBuildUpgrEx( 0,0,1, UPG_MELEE );
				SetBuildUpgrEx( 0,0,1, UPG_RANGED );
				SetBuildUpgrEx( 0,0,1, UPG_SORCERY );
				SetBuildUpgrEx( 1,1,1, UPG_GUN_RANGE );
				SetBuildUpgrEx( 0,0,1, UPG_BREEDING );
				SetBuildUpgrEx( 3,3,3, UPG_MASONRY );
				SetBuildUpgr ( 1, UPG_SENTINEL );
				WaitForSignal();
				allow_signal_abort = true;
				//*** WAVE 1 Time 2min ***
				InitAssaultGroup();
				CampaignAttackerEx(2,2,3, GRYPHON );
				SuicideOnPlayer(M3,user);
				//*** WAVE 2 Time 5min ***
				InitAssaultGroup();
				CampaignAttackerEx(3,3,4, GRYPHON );
				SuicideOnPlayer(M3,user);
				SetBuildUpgrEx( 0,0,1, UPG_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_LEATHER );
				//*** WAVE 3 Time 8min ***
				InitAssaultGroup();
				CampaignAttackerEx(4,4,5, GRYPHON );
				SuicideOnPlayer(M3,user);
				SetBuildUpgrEx( 1,1,1, UPG_HAMMERS );
				SetBuildUpgrEx( 1,1,2, UPG_MELEE );
				SetBuildUpgrEx( 1,1,2, UPG_RANGED );
				//*** WAVE 4 Time 11min ***
				InitAssaultGroup();
				CampaignAttackerEx(4,4,5, GRYPHON );
				SuicideOnPlayer(M3,kel);
				SetBuildUpgrEx( 1,1,2, UPG_ARMOR );
				SetBuildUpgrEx( 1,1,2, UPG_LEATHER );
				SetBuildUpgrEx( 1,1,2, UPG_SORCERY );
				//*** WAVE 5 Time 14min ***
				InitAssaultGroup();
				CampaignAttackerEx(5,5,6, GRYPHON );
				SuicideOnPlayer(M3,user);
				SetBuildUpgrEx( 1,1,1, UPG_BREEDING );
				SetBuildUpgrEx( 2,2,3, UPG_MELEE );
				SetBuildUpgrEx( 2,2,3, UPG_RANGED );
				SetBuildUpgrEx( 2,2,3, UPG_ARMOR );
				SetBuildUpgrEx( 2,2,3, UPG_LEATHER );
				SetBuildUpgrEx( 2,2,2, UPG_SORCERY );
				//*** WAVE 6 Time 17min ***
				InitAssaultGroup();
				CampaignAttackerEx(3,3,4, KNIGHT );
				CampaignAttackerEx(4,4,5, GRYPHON );
				SuicideOnPlayer(M3,user);
				//*** WAVE 7 Time 20min ***
				InitAssaultGroup();
				CampaignAttackerEx(4,4,5, KNIGHT );
				CampaignAttackerEx(4,4,5, GRYPHON );
				SuicideOnPlayer(M3,user);
				//*** WAVE 8 Time 23min ***
				InitAssaultGroup();
				CampaignAttackerEx(3,3,4, KNIGHT );
				CampaignAttackerEx(5,5,6, GRYPHON );
				CampaignAttackerEx(1,1,2, SORCERESS );
				SuicideOnPlayer(M3,user);
				//*** WAVE 9 Time 26min ***
				InitAssaultGroup();
				CampaignAttackerEx(3,3,4, KNIGHT );
				CampaignAttackerEx(5,5,6, GRYPHON );
				CampaignAttackerEx(1,1,2, SORCERESS );
				CampaignAttackerEx(1,1,2, MORTAR );
				CampaignAttackerEx(1,1,1, ARCHMAGE );
				SuicideOnPlayer(M3,kel);
				//*** WAVE 10 Time 29min ***
				InitAssaultGroup();
				CampaignAttackerEx(3,3,4, KNIGHT );
				CampaignAttackerEx(5,5,6, GRYPHON );
				CampaignAttackerEx(1,1,2, SORCERESS );
				CampaignAttackerEx(1,1,2, MORTAR );
				CampaignAttackerEx(1,1,1, ARCHMAGE );
				SuicideOnPlayer(M3,kel);
				SuicideUnits( RIFLEMAN, TANK, COPTER, MORTAR, FOOTMAN, KNIGHT, PRIEST, ARCHMAGE, GRYPHON, 0 );
			}

		} // class u08_blue_ai 

	}

