// Generated by .


	public partial class GameDefine 
	{

		public class u08_red_ai
		{
		//============================================================================
		//  Undead 08 -- Red (blue) player -- AI Script
		//============================================================================
			public BJPlayer  user = Player(3);
			public BJPlayer  kel = Player(6);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				do_campaign_farms = false;
				SetCaptainHome(ATTACK_CAPTAIN,5366,-1746);
				SetBuildUnit( 1, TOWN_HALL );
				SetBuildUnit( 2, PEASANT );
				SetBuildUnit( 3, BARRACKS );
				SetBuildUnit( 1, LUMBER_MILL );
				SetBuildUnit( 6, HOUSE );
				SetBuildUnit( 1, BLACKSMITH );
				SetBuildUnit( 5, PEASANT );
				SetBuildUnit( 1, WORKSHOP );
				SetBuildUnit( 1, KEEP );
				SetBuildUnit( 1, HUMAN_ALTAR );
				SetBuildUnit( 1, SANCTUM );
				SetBuildUnit( 1, CASTLE );
				SetBuildUnit( 1, WATCH_TOWER );
				SetBuildUnit( 3, CANNON_TOWER );
				SetBuildUnit( 2, GUARD_TOWER );
				CampaignDefender (EASY, 1, FOOTMAN );
				CampaignDefender (EASY, 1, KNIGHT );
				CampaignDefender (EASY, 1, RIFLEMAN );
				CampaignDefender (EASY, 1, PRIEST );
				CampaignDefender (EASY, 1, SORCERESS );
				CampaignDefender (EASY, 1, ARCHMAGE );
				SetBuildUpgrEx( 0,0,1, UPG_MELEE );
				SetBuildUpgrEx( 0,0,1, UPG_RANGED );
				SetBuildUpgrEx( 0,0,1, UPG_SORCERY );
				SetBuildUpgrEx( 0,0,1, UPG_PRAYING );
				SetBuildUpgrEx( 1,1,1, UPG_GUN_RANGE );
				SetBuildUpgrEx( 0,0,1, UPG_BREEDING );
				SetBuildUpgrEx( 3,3,3, UPG_MASONRY );
				SetBuildUpgr ( 1, UPG_SENTINEL );
				WaitForSignal();
				allow_signal_abort = true;
				//*** WAVE 1 Time 0min ***
				InitAssaultGroup();
				CampaignAttackerEx(2,2,2, FOOTMAN );
				CampaignAttackerEx(1,1,2, KNIGHT );
				CampaignAttackerEx(1,1,2, RIFLEMAN );
				SuicideOnPlayer(30,kel);
				SetBuildUpgrEx( 0,0,1, UPG_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_LEATHER );
				//*** WAVE 2 Time 4min ***
				InitAssaultGroup();
				CampaignAttackerEx(1,1,4, KNIGHT );
				CampaignAttackerEx(2,2,3, RIFLEMAN );
				CampaignAttackerEx(1,1,2, PRIEST );
				SuicideOnPlayer(M4,user);
				SetBuildUpgrEx( 1,1,2, UPG_MELEE );
				SetBuildUpgrEx( 1,1,2, UPG_RANGED );
				//*** WAVE 3 Time 7min ***
				InitAssaultGroup();
				CampaignAttackerEx(0,0,3, KNIGHT );
				CampaignAttackerEx(4,4,0, FOOTMAN );
				CampaignAttackerEx(0,0,2, RIFLEMAN );
				CampaignAttackerEx(2,2,2, SORCERESS );
				CampaignAttackerEx(1,1,1, ARCHMAGE );
				SuicideOnPlayer(M3,user);
				SetBuildUpgrEx( 1,1,2, UPG_ARMOR );
				SetBuildUpgrEx( 1,1,2, UPG_LEATHER );
				//*** WAVE 4 Time 11min ***
				InitAssaultGroup();
				CampaignAttackerEx(1,1,4, KNIGHT );
				CampaignAttackerEx(2,2,3, RIFLEMAN );
				CampaignAttackerEx(1,1,2, PRIEST );
				CampaignAttackerEx(1,1,2, MORTAR );
				SuicideOnPlayer(M4,user);
				SetBuildUpgrEx( 1,1,2, UPG_SORCERY );
				SetBuildUpgrEx( 1,1,2, UPG_PRAYING );
				//*** WAVE 5 Time 14min ***
				InitAssaultGroup();
				CampaignAttackerEx(0,0,2, KNIGHT );
				CampaignAttackerEx(5,5,4, RIFLEMAN );
				CampaignAttackerEx(2,2,2, SORCERESS );
				CampaignAttackerEx(1,1,1, ARCHMAGE );
				SuicideOnPlayer(M3,user);
				//*** WAVE 6 Time 18min ***
				InitAssaultGroup();
				CampaignAttackerEx(2,2,4, KNIGHT );
				CampaignAttackerEx(3,3,4, FOOTMAN );
				CampaignAttackerEx(2,2,2, PRIEST );
				CampaignAttackerEx(1,1,2, MORTAR );
				SuicideOnPlayer(M4,user);
				SetBuildUpgrEx( 1,1,1, UPG_BREEDING );
				SetBuildUpgrEx( 2,2,3, UPG_MELEE );
				SetBuildUpgrEx( 2,2,3, UPG_RANGED );
				//*** WAVE 7 Time 21min ***
				InitAssaultGroup();
				CampaignAttackerEx(2,2,4, KNIGHT );
				CampaignAttackerEx(2,2,4, RIFLEMAN );
				CampaignAttackerEx(1,1,2, MORTAR );
				CampaignAttackerEx(2,2,2, SORCERESS );
				CampaignAttackerEx(1,1,1, ARCHMAGE );
				SuicideOnPlayer(M3,kel);
				SetBuildUpgrEx( 2,2,3, UPG_ARMOR );
				SetBuildUpgrEx( 2,2,3, UPG_LEATHER );
				SetBuildUpgrEx( 2,2,2, UPG_SORCERY );
				SetBuildUpgrEx( 2,2,2, UPG_PRAYING );
				//*** WAVE 7 Time 25min ***
				InitAssaultGroup();
				CampaignAttackerEx(6,6,8, KNIGHT );
				CampaignAttackerEx(1,1,2, MORTAR );
				CampaignAttackerEx(2,2,2, PRIEST );
				CampaignAttackerEx(0,0,1, ARCHMAGE );
				SuicideOnPlayer(M4,user);
				//*** WAVE 7 Time 28min ***
				InitAssaultGroup();
				CampaignAttackerEx(2,2,4, KNIGHT );
				CampaignAttackerEx(2,2,4, RIFLEMAN );
				CampaignAttackerEx(1,1,2, MORTAR );
				CampaignAttackerEx(2,2,2, SORCERESS );
				CampaignAttackerEx(1,1,1, ARCHMAGE );
				SuicideOnPlayer(M3,kel);
				SuicideUnits( RIFLEMAN, TANK, COPTER, MORTAR, FOOTMAN, KNIGHT, PRIEST, ARCHMAGE, SORCERESS, 0 );
			}

		} // class u08_red_ai 

	}

