// Generated by .


	public partial class GameDefine 
	{

		public class u08x04_ai
		{
		//============================================================================
		//  $Id: u08x04.ai,v 1.14.2.4 2003/05/12 20:47:05 abond Exp $
		//============================================================================
			public int NO_CLOUD_HAWK = UnitId( "h000" );
			public int CLOUD_HAWK = HUMAN_DRAGON_HAWK;
			public BJPlayer  user = PlayerEx(1);
		//============================================================================
		//  main
		//============================================================================
			public void main(  )
			{
				// Original JassCode
				CampaignAI(HOUSE,null);
				SetReplacements(1,1,2);
				DoCampaignFarms(false);
				// phoenix goes into attack force once summoned
				GroupTimedLife(true);
				SetBuildUnitEx( 1,1,1, BLOOD_PEASANT );
				SetBuildUnitEx( 0,0,1, TOWN_HALL );
				SetBuildUnitEx( 0,0,1, HUMAN_ALTAR );
				SetBuildUnitEx( 0,0,4, WATCH_TOWER );
				SetBuildUnitEx( 0,0,1, LUMBER_MILL );
				SetBuildUnitEx( 0,0,4, GUARD_TOWER );
				SetBuildUnitEx( 0,0,1, ARCANE_VAULT );
				SetBuildUnitEx( 0,0,1, BLACKSMITH );
				SetBuildUnitEx( 0,0,1, KEEP );
				SetBuildUnitEx( 0,0,1, ARCANE_SANCTUM );
				SetBuildUnitEx( 0,0,0, CASTLE );
				SetBuildUnitEx( 0,0,0, AVIARY );
				SetBuildUnitEx( 8,8,8, BLOOD_PEASANT );
				CampaignDefenderEx( 0,0,1, KAEL );
				CampaignDefenderEx( 1,1,1, SPELL_BREAKER );
				CampaignDefenderEx( 1,1,2, HIGH_SWORDMAN );
				CampaignDefenderEx( 0,0,1, SORCERESS );
				CampaignDefenderEx( 1,1,1, PRIEST );
				CampaignDefenderEx( 1,1,2, HIGH_ARCHER );
				SetBuildUpgrEx( 0,0,1, UPG_SORCERY );
				SetBuildUpgrEx( 0,0,1, UPG_PRAYING );
				SetBuildUpgrEx( 1,1,3, UPG_MASONRY );
				SetBuildUpgrEx( 1,1,1, UPG_CLOUD );
				//*** WAVE 1 ***
				InitAssaultGroup();
				CampaignAttackerEx( 3,3,5, HIGH_SWORDMAN );
				CampaignAttackerEx( 2,2,3, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,2, BALLISTA );
				SuicideOnPlayerEx(M4,M4,M3,user);
				SetBuildUpgrEx( 0,0,1, UPG_ARMOR );
				SetBuildUpgrEx( 0,0,1, UPG_LEATHER );
				//*** WAVE 2 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,5, SPELL_BREAKER );
				CampaignAttackerEx( 2,2,3, HIGH_ARCHER );
				SuicideOnPlayerEx(M4,M4,M7,user);
				SetBuildUpgrEx( 0,0,1, UPG_RANGED );
				SetBuildUpgrEx( 0,0,1, UPG_MELEE );
				SetBuildUpgrEx( 1,1,2, UPG_SORCERY );
				SetBuildUpgrEx( 1,1,2, UPG_PRAYING );
				//*** WAVE 3 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, HIGH_SWORDMAN );
				CampaignAttackerEx( 1,1,2, PRIEST );
				CampaignAttackerEx( 1,1,1, KAEL );
				SuicideOnPlayerEx(M8,M8,M8,user);
				SetBuildUpgrEx( 1,1,3, UPG_ARMOR );
				SetBuildUpgrEx( 1,1,3, UPG_LEATHER );
				//*** WAVE 4 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,3, CLOUD_HAWK );
				CampaignAttackerEx( 4,4,7, NO_CLOUD_HAWK );
				SuicideOnPlayerEx(M4,M4,M2,user);
				SetBuildUpgrEx( 1,1,3, UPG_RANGED );
				SetBuildUpgrEx( 1,1,3, UPG_MELEE );
				SetBuildUpgrEx( 2,2,2, UPG_SORCERY );
				SetBuildUpgrEx( 2,2,2, UPG_PRAYING );
				SetBuildUpgrEx( 1,1,1, UPG_CONT_MAGIC );
				//*** WAVE 5 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, SPELL_BREAKER );
				CampaignAttackerEx( 0,0,2, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,1, BALLISTA );
				CampaignAttackerEx( 2,2,4, SORCERESS );
				SuicideOnPlayerEx(M6,M6,M9,user);
				//*** WAVE 6 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, HIGH_SWORDMAN );
				CampaignAttackerEx( 2,2,4, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,2, PRIEST );
				CampaignAttackerEx( 0,0,1, KAEL );
				CampaignAttackerEx( 1,1,1, CLOUD_HAWK );
				SuicideOnPlayerEx(M6,M6,M7,user);
				//*** WAVE 7 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, SPELL_BREAKER );
				CampaignAttackerEx( 0,0,2, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,1, BALLISTA );
				CampaignAttackerEx( 2,2,4, SORCERESS );
				CampaignAttackerEx( 1,1,1, KAEL );
				SuicideOnPlayerEx(M7,M7,M7,user);
				//*** WAVE 8 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,4, HIGH_SWORDMAN );
				CampaignAttackerEx( 2,2,2, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,2, PRIEST );
				CampaignAttackerEx( 1,1,2, SORCERESS );
				CampaignAttackerEx( 1,1,0, KAEL );
				SuicideOnPlayerEx(M8,M8,M3,user);
				//*** WAVE 9 ***
				InitAssaultGroup();
				CampaignAttackerEx( 2,2,3, CLOUD_HAWK );
				CampaignAttackerEx( 4,4,7, NO_CLOUD_HAWK );
				SuicideOnPlayerEx(M8,M8,M9,user);
				//*** WAVE 10 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, SPELL_BREAKER );
				CampaignAttackerEx( 0,0,2, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,1, BALLISTA );
				CampaignAttackerEx( 2,2,4, SORCERESS );
				CampaignAttackerEx( 0,0,1, KAEL );
				SuicideOnPlayerEx(M4,M4,M7,user);
				//*** WAVE 11 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, HIGH_SWORDMAN );
				CampaignAttackerEx( 2,2,4, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,2, PRIEST );
				CampaignAttackerEx( 0,0,1, KAEL );
				CampaignAttackerEx( 1,1,1, CLOUD_HAWK );
				SuicideOnPlayerEx(M7,M7,M7,user);
				//*** WAVE 12 ***
				InitAssaultGroup();
				CampaignAttackerEx( 4,4,6, SPELL_BREAKER );
				CampaignAttackerEx( 0,0,2, HIGH_ARCHER );
				CampaignAttackerEx( 1,1,1, BALLISTA );
				CampaignAttackerEx( 2,2,4, SORCERESS );
				CampaignAttackerEx( 1,1,0, KAEL );
				SuicideOnPlayerEx(M8,M8,M3,user);
				while( true )
				{
					//*** WAVE 13 ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,3, CLOUD_HAWK );
					CampaignAttackerEx( 4,4,7, NO_CLOUD_HAWK );
					SuicideOnPlayerEx(M8,M8,M9,user);
					//*** WAVE 14 ***
					InitAssaultGroup();
					CampaignAttackerEx( 4,4,4, HIGH_SWORDMAN );
					CampaignAttackerEx( 2,2,2, HIGH_ARCHER );
					CampaignAttackerEx( 1,1,2, PRIEST );
					CampaignAttackerEx( 1,1,2, SORCERESS );
					CampaignAttackerEx( 1,1,1, KAEL );
					CampaignAttackerEx( 1,1,1, CLOUD_HAWK );
					SuicideOnPlayerEx(M8,M8,M7,user);
					//*** WAVE 15 ***
					InitAssaultGroup();
					CampaignAttackerEx( 4,4,6, SPELL_BREAKER );
					CampaignAttackerEx( 0,0,2, HIGH_ARCHER );
					CampaignAttackerEx( 1,1,1, BALLISTA );
					CampaignAttackerEx( 2,2,4, SORCERESS );
					CampaignAttackerEx( 0,0,1, KAEL );
					SuicideOnPlayerEx(M8,M8,M7,user);
					//*** WAVE 16 ***
					InitAssaultGroup();
					CampaignAttackerEx( 2,2,3, CLOUD_HAWK );
					CampaignAttackerEx( 4,4,7, NO_CLOUD_HAWK );
					SuicideOnPlayerEx(M8,M8,M3,user);
				}
			}

		} // class u08x04_ai 

	}

