// Generated by .


	public partial class GameDefine 
	{

		public class Undead02Interlude_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "Splats\\SplatData.slk" );
				Preload( "ReplaceableTextures\\Splats\\Splat01Mature.blp" );
				Preload( "TerrainArt\\Weather.slk" );
				Preload( "ReplaceableTextures\\Weather\\CloudSingleFlat.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor05.blp" );
				Preload( "ReplaceableTextures\\TeamGlow\\TeamGlow05.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor01.blp" );
				Preload( "ReplaceableTextures\\TeamGlow\\TeamGlow01.blp" );
				Preload( "Sound\\Dialogue\\UndeadCampaign\\Undead02Interlude\\U02DreadlordA32.mp3" );
				Preload( "Sound\\Dialogue\\UndeadCampaign\\Undead02Interlude\\U02Tichondrius33.mp3" );
				Preload( "Sound\\Dialogue\\UndeadCampaign\\Undead02Interlude\\U02DreadlordB34.mp3" );
				Preload( "Sound\\Dialogue\\UndeadCampaign\\Undead02Interlude\\U02DreadlordA35.mp3" );
				Preload( "Sound\\Dialogue\\UndeadCampaign\\Undead02Interlude\\U02Tichondrius36.mp3" );
				Preload( "Sound\\Dialogue\\UndeadCampaign\\Undead02Interlude\\U02DreadlordA37.mp3" );
				Preload( "ReplaceableTextures\\CameraMasks\\White_mask.blp" );
				Preload( "Sound\\Buildings\\Fire\\OrcHumanSmallBuildingFire1.wav" );
				Preload( "UI\\TipStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\Undead\\undead-options-button-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-up.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Undead\\undead-options-button-background-down.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-border-down.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Undead\\undead-options-button-background-disabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Undead\\undead-options-button-border-disabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\human-options-button-background-disabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\editbox-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-border.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Undead\\undead-slider-knob.blp" );
				Preload( "UI\\HelpStrings.txt" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-borderdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\slider-knobdisabled.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Undead\\undead-checkbox-depressed.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\checkbox-background-disabled.blp" );
				Preload( "UI\\Widgets\\Glues\\GlueScreen-PullDown-Arrow.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-gold.blp" );
				Preload( "UI\\Widgets\\EscMenu\\Human\\alliance-lumber.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor02.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor04.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor06.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor07.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor08.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor09.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor10.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor11.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor12.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor13.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor14.blp" );
				Preload( "war3mapMap.blp" );
				Preload( "UI\\Minimap\\minimap-gold.blp" );
				Preload( "UI\\Minimap\\minimap-neutralbuilding.blp" );
				Preload( "UI\\Minimap\\MinimapIconCircleOfPower.blp" );
				Preload( "UI\\Minimap\\minimap-hero.blp" );
				Preload( "Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdx" );
				Preload( "Doodads\\Terrain\\CliffDoodad\\CliffDoodadCave\\CliffDoodadCave.mdx" );
				Preload( "Textures\\CaveCliffDoodad.blp" );
				Preload( "Sound\\Ambient\\DoodadEffects\\WaterWaterFallLoop1.wav" );
				Preload( "Sound\\Buildings\\Fire\\OrcHumanMediumBuildingFire1.wav" );
				Preload( "Sound\\Ambient\\DoodadEffects\\LordaeronSummerHumanTorchLoop1.wav" );
				Preload( "Abilities\\Spells\\Undead\\Darksummoning\\DarkSummonTarget.mdx" );
				Preload( "Textures\\GenericGlow2_64_blue.blp" );
				Preload( "Splats\\UberSplatData.slk" );
				Preload( "ReplaceableTextures\\Splats\\DarkSummonSpecial.blp" );
				Preload( "Abilities\\Spells\\Undead\\DarkSummoning\\DarkSummonMissile.mdx" );
				Preload( "Textures\\Ghost2.blp" );
				Preload( "Textures\\GenericGlow64.blp" );
				Preload( "ReplaceableTextures\\Selection\\SelectionCircleMed.blp" );
				PreloadEnd( 5.0 );
			}

		} // class Undead02Interlude_pld 

	}

