// Generated by .


	public partial class GameDefine 
	{

		public class WarChasers_pld
		{
			public void PreloadFiles(  )
			{
				// Original JassCode
				Preload( "Splats\\SplatData.slk" );
				Preload( "ReplaceableTextures\\Splats\\Splat01Mature.blp" );
				Preload( "UI\\TipStrings.txt" );
				Preload( "UI\\HelpStrings.txt" );
				Preload( "UI\\Widgets\\Glues\\GlueScreen-PullDown-Arrow.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor02.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor03.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor04.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor07.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor08.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor09.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor10.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor13.blp" );
				Preload( "ReplaceableTextures\\TeamColor\\TeamColor14.blp" );
				Preload( "war3mapMap.blp" );
				Preload( "UI\\Minimap\\minimap-gold.blp" );
				Preload( "UI\\Minimap\\minimap-neutralbuilding.blp" );
				Preload( "UI\\Minimap\\MinimapIconCircleOfPower.blp" );
				Preload( "UI\\Minimap\\minimap-hero.blp" );
				Preload( "Sound\\Ambient\\DoodadEffects\\CityScapeMagicRunesLoop1.wav" );
				Preload( "Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdl" );
				Preload( "Abilities\\Spells\\Other\\GeneralAuraTarget\\GeneralAuraTarget.mdx" );
				Preload( "Abilities\\Weapons\\SludgeMissile\\SludgeMissile.mdl" );
				Preload( "Abilities\\Weapons\\SludgeMissile\\SludgeMissile.mdx" );
				Preload( "Sound\\Buildings\\Fire\\OrcHumanMediumBuildingFire1.wav" );
				Preload( "Units\\Critters\\OrcJuggernaught\\OrcJuggernaught.mdl" );
				Preload( "Units\\Critters\\OrcJuggernaught\\OrcJuggernaught.mdx" );
				Preload( "units\\Critters\\OrcJuggernaught\\Orc_juggernaught.blp" );
				Preload( "Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget.mdl" );
				Preload( "Abilities\\Spells\\Undead\\FrostArmor\\FrostArmorTarget.mdx" );
				Preload( "Textures\\Ghost2.blp" );
				Preload( "units\\creeps\\Murloc\\Murloc.mdl" );
				Preload( "units\\creeps\\Murloc\\Murloc.mdx" );
				Preload( "units\\Creeps\\Murloc\\Murloc.blp" );
				Preload( "units\\creeps\\GnollArcher\\GnollArcher.mdl" );
				Preload( "units\\creeps\\GnollArcher\\GnollArcher.mdx" );
				Preload( "Textures\\gnoll.blp" );
				Preload( "units\\creeps\\Satyr\\Satyr.mdl" );
				Preload( "units\\creeps\\Satyr\\Satyr.mdx" );
				Preload( "units\\undead\\Ghoul\\Ghoul.mdl" );
				Preload( "units\\undead\\Ghoul\\Ghoul.mdx" );
				Preload( "units\\Undead\\Ghoul\\Ghoul.blp" );
				Preload( "Textures\\Peasant.blp" );
				Preload( "units\\creeps\\MurlocWarrior\\MurlocWarrior.mdl" );
				Preload( "units\\creeps\\MurlocWarrior\\MurlocWarrior.mdx" );
				Preload( "units\\Creeps\\MurlocWarrior\\MurlocWarrior.blp" );
				Preload( "units\\creeps\\CorruptedEnt\\CorruptedEnt.mdl" );
				Preload( "units\\creeps\\CorruptedEnt\\CorruptedEnt.mdx" );
				Preload( "units\\Creeps\\CorruptedEnt\\CorruptedEnt.blp" );
				Preload( "units\\creeps\\IceTrollShadowPriest\\IceTrollShadowPriest.mdl" );
				Preload( "units\\creeps\\IceTrollShadowPriest\\IceTrollShadowPriest.mdx" );
				Preload( "units\\Creeps\\IceTrollShadowPriest\\IceTrollShadowPriest.blp" );
				Preload( "units\\demon\\felhound\\felhound.mdl" );
				Preload( "units\\demon\\felhound\\felhound.mdx" );
				Preload( "units\\Demon\\felhound\\FelHound.blp" );
				PreloadEnd( 5.0 );
			}

		} // class WarChasers_pld 

	}

